// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/badge.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/badge.go -destination=./internal/mock/mock_usecase/badge.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	usecase "github.com/vsrecorder/core-apiserver/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockBadgeInterface is a mock of BadgeInterface interface.
type MockBadgeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBadgeInterfaceMockRecorder
	isgomock struct{}
}

// MockBadgeInterfaceMockRecorder is the mock recorder for MockBadgeInterface.
type MockBadgeInterfaceMockRecorder struct {
	mock *MockBadgeInterface
}

// NewMockBadgeInterface creates a new mock instance.
func NewMockBadgeInterface(ctrl *gomock.Controller) *MockBadgeInterface {
	mock := &MockBadgeInterface{ctrl: ctrl}
	mock.recorder = &MockBadgeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBadgeInterface) EXPECT() *MockBadgeInterfaceMockRecorder {
	return m.recorder
}

// GetAllDefinitions mocks base method.
func (m *MockBadgeInterface) GetAllDefinitions(ctx context.Context) ([]*entity.BadgeDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDefinitions", ctx)
	ret0, _ := ret[0].([]*entity.BadgeDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDefinitions indicates an expected call of GetAllDefinitions.
func (mr *MockBadgeInterfaceMockRecorder) GetAllDefinitions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDefinitions", reflect.TypeOf((*MockBadgeInterface)(nil).GetAllDefinitions), ctx)
}

// GetByUserId mocks base method.
func (m *MockBadgeInterface) GetByUserId(ctx context.Context, userId, season string) ([]*usecase.UserBadgeView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserId", ctx, userId, season)
	ret0, _ := ret[0].([]*usecase.UserBadgeView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserId indicates an expected call of GetByUserId.
func (mr *MockBadgeInterfaceMockRecorder) GetByUserId(ctx, userId, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserId", reflect.TypeOf((*MockBadgeInterface)(nil).GetByUserId), ctx, userId, season)
}
