// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/calendar.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/calendar.go -destination=./internal/mock/mock_usecase/calendar.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCalendarInterface is a mock of CalendarInterface interface.
type MockCalendarInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCalendarInterfaceMockRecorder
	isgomock struct{}
}

// MockCalendarInterfaceMockRecorder is the mock recorder for MockCalendarInterface.
type MockCalendarInterfaceMockRecorder struct {
	mock *MockCalendarInterface
}

// NewMockCalendarInterface creates a new mock instance.
func NewMockCalendarInterface(ctrl *gomock.Controller) *MockCalendarInterface {
	mock := &MockCalendarInterface{ctrl: ctrl}
	mock.recorder = &MockCalendarInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalendarInterface) EXPECT() *MockCalendarInterfaceMockRecorder {
	return m.recorder
}

// GetCalendar mocks base method.
func (m *MockCalendarInterface) GetCalendar(ctx context.Context, userId string) (*entity.Calendar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCalendar", ctx, userId)
	ret0, _ := ret[0].(*entity.Calendar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCalendar indicates an expected call of GetCalendar.
func (mr *MockCalendarInterfaceMockRecorder) GetCalendar(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCalendar", reflect.TypeOf((*MockCalendarInterface)(nil).GetCalendar), ctx, userId)
}
