// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/cityleague_schedule.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/cityleague_schedule.go -destination=./internal/mock/mock_usecase/cityleague_schedule.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCityleagueScheduleInterface is a mock of CityleagueScheduleInterface interface.
type MockCityleagueScheduleInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCityleagueScheduleInterfaceMockRecorder
	isgomock struct{}
}

// MockCityleagueScheduleInterfaceMockRecorder is the mock recorder for MockCityleagueScheduleInterface.
type MockCityleagueScheduleInterfaceMockRecorder struct {
	mock *MockCityleagueScheduleInterface
}

// NewMockCityleagueScheduleInterface creates a new mock instance.
func NewMockCityleagueScheduleInterface(ctrl *gomock.Controller) *MockCityleagueScheduleInterface {
	mock := &MockCityleagueScheduleInterface{ctrl: ctrl}
	mock.recorder = &MockCityleagueScheduleInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCityleagueScheduleInterface) EXPECT() *MockCityleagueScheduleInterfaceMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockCityleagueScheduleInterface) Find(ctx context.Context) ([]*entity.CityleagueSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]*entity.CityleagueSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCityleagueScheduleInterfaceMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCityleagueScheduleInterface)(nil).Find), ctx)
}

// FindByDate mocks base method.
func (m *MockCityleagueScheduleInterface) FindByDate(ctx context.Context, date time.Time) (*entity.CityleagueSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDate", ctx, date)
	ret0, _ := ret[0].(*entity.CityleagueSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDate indicates an expected call of FindByDate.
func (mr *MockCityleagueScheduleInterfaceMockRecorder) FindByDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDate", reflect.TypeOf((*MockCityleagueScheduleInterface)(nil).FindByDate), ctx, date)
}

// FindById mocks base method.
func (m *MockCityleagueScheduleInterface) FindById(ctx context.Context, id string) (*entity.CityleagueSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*entity.CityleagueSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockCityleagueScheduleInterfaceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockCityleagueScheduleInterface)(nil).FindById), ctx, id)
}
