// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/deck_usage_stat.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/deck_usage_stat.go -destination=./internal/mock/mock_usecase/deck_usage_stat.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDeckUsageStatInterface is a mock of DeckUsageStatInterface interface.
type MockDeckUsageStatInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeckUsageStatInterfaceMockRecorder
	isgomock struct{}
}

// MockDeckUsageStatInterfaceMockRecorder is the mock recorder for MockDeckUsageStatInterface.
type MockDeckUsageStatInterfaceMockRecorder struct {
	mock *MockDeckUsageStatInterface
}

// NewMockDeckUsageStatInterface creates a new mock instance.
func NewMockDeckUsageStatInterface(ctrl *gomock.Controller) *MockDeckUsageStatInterface {
	mock := &MockDeckUsageStatInterface{ctrl: ctrl}
	mock.recorder = &MockDeckUsageStatInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeckUsageStatInterface) EXPECT() *MockDeckUsageStatInterfaceMockRecorder {
	return m.recorder
}

// GetDeckUsageStat mocks base method.
func (m *MockDeckUsageStatInterface) GetDeckUsageStat(ctx context.Context, userId, yearMonth, environmentId, season, regulationId string, allTime bool) (*entity.DeckUsageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeckUsageStat", ctx, userId, yearMonth, environmentId, season, regulationId, allTime)
	ret0, _ := ret[0].(*entity.DeckUsageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeckUsageStat indicates an expected call of GetDeckUsageStat.
func (mr *MockDeckUsageStatInterfaceMockRecorder) GetDeckUsageStat(ctx, userId, yearMonth, environmentId, season, regulationId, allTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeckUsageStat", reflect.TypeOf((*MockDeckUsageStatInterface)(nil).GetDeckUsageStat), ctx, userId, yearMonth, environmentId, season, regulationId, allTime)
}
