// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/deck_code.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/deck_code.go -destination=./internal/mock/mock_usecase/deck_code.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	usecase "github.com/vsrecorder/core-apiserver/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockDeckCodeInterface is a mock of DeckCodeInterface interface.
type MockDeckCodeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeckCodeInterfaceMockRecorder
	isgomock struct{}
}

// MockDeckCodeInterfaceMockRecorder is the mock recorder for MockDeckCodeInterface.
type MockDeckCodeInterfaceMockRecorder struct {
	mock *MockDeckCodeInterface
}

// NewMockDeckCodeInterface creates a new mock instance.
func NewMockDeckCodeInterface(ctrl *gomock.Controller) *MockDeckCodeInterface {
	mock := &MockDeckCodeInterface{ctrl: ctrl}
	mock.recorder = &MockDeckCodeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeckCodeInterface) EXPECT() *MockDeckCodeInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeckCodeInterface) Create(ctx context.Context, param *usecase.DeckCodeCreateParam) (*entity.DeckCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, param)
	ret0, _ := ret[0].(*entity.DeckCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDeckCodeInterfaceMockRecorder) Create(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeckCodeInterface)(nil).Create), ctx, param)
}

// Delete mocks base method.
func (m *MockDeckCodeInterface) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeckCodeInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeckCodeInterface)(nil).Delete), ctx, id)
}

// FindByDeckId mocks base method.
func (m *MockDeckCodeInterface) FindByDeckId(ctx context.Context, deckId string) ([]*entity.DeckCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDeckId", ctx, deckId)
	ret0, _ := ret[0].([]*entity.DeckCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDeckId indicates an expected call of FindByDeckId.
func (mr *MockDeckCodeInterfaceMockRecorder) FindByDeckId(ctx, deckId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDeckId", reflect.TypeOf((*MockDeckCodeInterface)(nil).FindByDeckId), ctx, deckId)
}

// FindById mocks base method.
func (m *MockDeckCodeInterface) FindById(ctx context.Context, id string) (*entity.DeckCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*entity.DeckCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockDeckCodeInterfaceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockDeckCodeInterface)(nil).FindById), ctx, id)
}

// Update mocks base method.
func (m *MockDeckCodeInterface) Update(ctx context.Context, id string, param *usecase.DeckCodeUpdateParam) (*entity.DeckCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, param)
	ret0, _ := ret[0].(*entity.DeckCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDeckCodeInterfaceMockRecorder) Update(ctx, id, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeckCodeInterface)(nil).Update), ctx, id, param)
}
