// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/deck_code_post.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/deck_code_post.go -destination=./internal/mock/mock_usecase/deck_code_post.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	usecase "github.com/vsrecorder/core-apiserver/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockDeckCodePostInterface is a mock of DeckCodePostInterface interface.
type MockDeckCodePostInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeckCodePostInterfaceMockRecorder
	isgomock struct{}
}

// MockDeckCodePostInterfaceMockRecorder is the mock recorder for MockDeckCodePostInterface.
type MockDeckCodePostInterfaceMockRecorder struct {
	mock *MockDeckCodePostInterface
}

// NewMockDeckCodePostInterface creates a new mock instance.
func NewMockDeckCodePostInterface(ctrl *gomock.Controller) *MockDeckCodePostInterface {
	mock := &MockDeckCodePostInterface{ctrl: ctrl}
	mock.recorder = &MockDeckCodePostInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeckCodePostInterface) EXPECT() *MockDeckCodePostInterfaceMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockDeckCodePostInterface) Find(ctx context.Context, param *usecase.DeckCodePostFindParam) (*usecase.DeckCodePostFindResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, param)
	ret0, _ := ret[0].(*usecase.DeckCodePostFindResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockDeckCodePostInterfaceMockRecorder) Find(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockDeckCodePostInterface)(nil).Find), ctx, param)
}

// FindAceSpecCounts mocks base method.
func (m *MockDeckCodePostInterface) FindAceSpecCounts(ctx context.Context, environmentId string) (*usecase.DeckCodePostAceSpecCountsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAceSpecCounts", ctx, environmentId)
	ret0, _ := ret[0].(*usecase.DeckCodePostAceSpecCountsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAceSpecCounts indicates an expected call of FindAceSpecCounts.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindAceSpecCounts(ctx, environmentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAceSpecCounts", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindAceSpecCounts), ctx, environmentId)
}

// FindActiveByDeckId mocks base method.
func (m *MockDeckCodePostInterface) FindActiveByDeckId(ctx context.Context, deckId string) ([]*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByDeckId", ctx, deckId)
	ret0, _ := ret[0].([]*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByDeckId indicates an expected call of FindActiveByDeckId.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindActiveByDeckId(ctx, deckId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByDeckId", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindActiveByDeckId), ctx, deckId)
}

// FindById mocks base method.
func (m *MockDeckCodePostInterface) FindById(ctx context.Context, id, viewerUserId string) (*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id, viewerUserId)
	ret0, _ := ret[0].(*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindById(ctx, id, viewerUserId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindById), ctx, id, viewerUserId)
}

// FindByUserId mocks base method.
func (m *MockDeckCodePostInterface) FindByUserId(ctx context.Context, uid, viewerUserId string, limit, offset int) (*usecase.DeckCodePostUserView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, uid, viewerUserId, limit, offset)
	ret0, _ := ret[0].(*usecase.DeckCodePostUserView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindByUserId(ctx, uid, viewerUserId, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindByUserId), ctx, uid, viewerUserId, limit, offset)
}

// FindLikers mocks base method.
func (m *MockDeckCodePostInterface) FindLikers(ctx context.Context, postId string, limit, offset int) ([]*entity.DeckCodePostLiker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLikers", ctx, postId, limit, offset)
	ret0, _ := ret[0].([]*entity.DeckCodePostLiker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLikers indicates an expected call of FindLikers.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindLikers(ctx, postId, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLikers", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindLikers), ctx, postId, limit, offset)
}

// Like mocks base method.
func (m *MockDeckCodePostInterface) Like(ctx context.Context, id, uid string) (*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, id, uid)
	ret0, _ := ret[0].(*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Like indicates an expected call of Like.
func (mr *MockDeckCodePostInterfaceMockRecorder) Like(ctx, id, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockDeckCodePostInterface)(nil).Like), ctx, id, uid)
}

// Publish mocks base method.
func (m *MockDeckCodePostInterface) Publish(ctx context.Context, uid, deckCodeId string) (*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, uid, deckCodeId)
	ret0, _ := ret[0].(*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockDeckCodePostInterfaceMockRecorder) Publish(ctx, uid, deckCodeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockDeckCodePostInterface)(nil).Publish), ctx, uid, deckCodeId)
}

// RecordImport mocks base method.
func (m *MockDeckCodePostInterface) RecordImport(ctx context.Context, id, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordImport", ctx, id, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordImport indicates an expected call of RecordImport.
func (mr *MockDeckCodePostInterfaceMockRecorder) RecordImport(ctx, id, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordImport", reflect.TypeOf((*MockDeckCodePostInterface)(nil).RecordImport), ctx, id, uid)
}

// Unlike mocks base method.
func (m *MockDeckCodePostInterface) Unlike(ctx context.Context, id, uid string) (*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlike", ctx, id, uid)
	ret0, _ := ret[0].(*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unlike indicates an expected call of Unlike.
func (mr *MockDeckCodePostInterfaceMockRecorder) Unlike(ctx, id, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlike", reflect.TypeOf((*MockDeckCodePostInterface)(nil).Unlike), ctx, id, uid)
}

// Unpublish mocks base method.
func (m *MockDeckCodePostInterface) Unpublish(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpublish", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unpublish indicates an expected call of Unpublish.
func (mr *MockDeckCodePostInterfaceMockRecorder) Unpublish(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpublish", reflect.TypeOf((*MockDeckCodePostInterface)(nil).Unpublish), ctx, id)
}
