// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/designation.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/designation.go -destination=./internal/mock/mock_usecase/designation.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	usecase "github.com/vsrecorder/core-apiserver/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockDesignationInterface is a mock of DesignationInterface interface.
type MockDesignationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDesignationInterfaceMockRecorder
	isgomock struct{}
}

// MockDesignationInterfaceMockRecorder is the mock recorder for MockDesignationInterface.
type MockDesignationInterfaceMockRecorder struct {
	mock *MockDesignationInterface
}

// NewMockDesignationInterface creates a new mock instance.
func NewMockDesignationInterface(ctrl *gomock.Controller) *MockDesignationInterface {
	mock := &MockDesignationInterface{ctrl: ctrl}
	mock.recorder = &MockDesignationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDesignationInterface) EXPECT() *MockDesignationInterfaceMockRecorder {
	return m.recorder
}

// GetAllDefinitions mocks base method.
func (m *MockDesignationInterface) GetAllDefinitions(ctx context.Context) ([]*entity.Designation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDefinitions", ctx)
	ret0, _ := ret[0].([]*entity.Designation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDefinitions indicates an expected call of GetAllDefinitions.
func (mr *MockDesignationInterfaceMockRecorder) GetAllDefinitions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDefinitions", reflect.TypeOf((*MockDesignationInterface)(nil).GetAllDefinitions), ctx)
}

// GetByUserId mocks base method.
func (m *MockDesignationInterface) GetByUserId(ctx context.Context, userId, season string) (*usecase.UserDesignationView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserId", ctx, userId, season)
	ret0, _ := ret[0].(*usecase.UserDesignationView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserId indicates an expected call of GetByUserId.
func (mr *MockDesignationInterfaceMockRecorder) GetByUserId(ctx, userId, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserId", reflect.TypeOf((*MockDesignationInterface)(nil).GetByUserId), ctx, userId, season)
}

// GetRankStats mocks base method.
func (m *MockDesignationInterface) GetRankStats(ctx context.Context, season string) (*usecase.DesignationRankStatsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRankStats", ctx, season)
	ret0, _ := ret[0].(*usecase.DesignationRankStatsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRankStats indicates an expected call of GetRankStats.
func (mr *MockDesignationInterfaceMockRecorder) GetRankStats(ctx, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRankStats", reflect.TypeOf((*MockDesignationInterface)(nil).GetRankStats), ctx, season)
}
