// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/environment_badge.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/environment_badge.go -destination=./internal/mock/mock_usecase/environment_badge.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	usecase "github.com/vsrecorder/core-apiserver/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockEnvironmentBadgeInterface is a mock of EnvironmentBadgeInterface interface.
type MockEnvironmentBadgeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEnvironmentBadgeInterfaceMockRecorder
	isgomock struct{}
}

// MockEnvironmentBadgeInterfaceMockRecorder is the mock recorder for MockEnvironmentBadgeInterface.
type MockEnvironmentBadgeInterfaceMockRecorder struct {
	mock *MockEnvironmentBadgeInterface
}

// NewMockEnvironmentBadgeInterface creates a new mock instance.
func NewMockEnvironmentBadgeInterface(ctrl *gomock.Controller) *MockEnvironmentBadgeInterface {
	mock := &MockEnvironmentBadgeInterface{ctrl: ctrl}
	mock.recorder = &MockEnvironmentBadgeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvironmentBadgeInterface) EXPECT() *MockEnvironmentBadgeInterfaceMockRecorder {
	return m.recorder
}

// GetByUserId mocks base method.
func (m *MockEnvironmentBadgeInterface) GetByUserId(ctx context.Context, userId string) ([]*usecase.EnvironmentBadgeView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserId", ctx, userId)
	ret0, _ := ret[0].([]*usecase.EnvironmentBadgeView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserId indicates an expected call of GetByUserId.
func (mr *MockEnvironmentBadgeInterfaceMockRecorder) GetByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserId", reflect.TypeOf((*MockEnvironmentBadgeInterface)(nil).GetByUserId), ctx, userId)
}
