// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/kizuna.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/kizuna.go -destination=./internal/mock/mock_usecase/kizuna.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockKizunaInterface is a mock of KizunaInterface interface.
type MockKizunaInterface struct {
	ctrl     *gomock.Controller
	recorder *MockKizunaInterfaceMockRecorder
	isgomock struct{}
}

// MockKizunaInterfaceMockRecorder is the mock recorder for MockKizunaInterface.
type MockKizunaInterfaceMockRecorder struct {
	mock *MockKizunaInterface
}

// NewMockKizunaInterface creates a new mock instance.
func NewMockKizunaInterface(ctrl *gomock.Controller) *MockKizunaInterface {
	mock := &MockKizunaInterface{ctrl: ctrl}
	mock.recorder = &MockKizunaInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKizunaInterface) EXPECT() *MockKizunaInterfaceMockRecorder {
	return m.recorder
}

// GetKizuna mocks base method.
func (m *MockKizunaInterface) GetKizuna(ctx context.Context, userId string) (*entity.Kizuna, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKizuna", ctx, userId)
	ret0, _ := ret[0].(*entity.Kizuna)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKizuna indicates an expected call of GetKizuna.
func (mr *MockKizunaInterfaceMockRecorder) GetKizuna(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKizuna", reflect.TypeOf((*MockKizunaInterface)(nil).GetKizuna), ctx, userId)
}
