// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/notification.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/notification.go -destination=./internal/mock/mock_usecase/notification.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationInterface is a mock of NotificationInterface interface.
type MockNotificationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationInterfaceMockRecorder
	isgomock struct{}
}

// MockNotificationInterfaceMockRecorder is the mock recorder for MockNotificationInterface.
type MockNotificationInterfaceMockRecorder struct {
	mock *MockNotificationInterface
}

// NewMockNotificationInterface creates a new mock instance.
func NewMockNotificationInterface(ctrl *gomock.Controller) *MockNotificationInterface {
	mock := &MockNotificationInterface{ctrl: ctrl}
	mock.recorder = &MockNotificationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationInterface) EXPECT() *MockNotificationInterfaceMockRecorder {
	return m.recorder
}

// CountUnreadByUserId mocks base method.
func (m *MockNotificationInterface) CountUnreadByUserId(ctx context.Context, userId string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnreadByUserId", ctx, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnreadByUserId indicates an expected call of CountUnreadByUserId.
func (mr *MockNotificationInterfaceMockRecorder) CountUnreadByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnreadByUserId", reflect.TypeOf((*MockNotificationInterface)(nil).CountUnreadByUserId), ctx, userId)
}

// ListByUserId mocks base method.
func (m *MockNotificationInterface) ListByUserId(ctx context.Context, userId string, limit int) ([]*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserId", ctx, userId, limit)
	ret0, _ := ret[0].([]*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserId indicates an expected call of ListByUserId.
func (mr *MockNotificationInterfaceMockRecorder) ListByUserId(ctx, userId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserId", reflect.TypeOf((*MockNotificationInterface)(nil).ListByUserId), ctx, userId, limit)
}

// MarkAllAsRead mocks base method.
func (m *MockNotificationInterface) MarkAllAsRead(ctx context.Context, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllAsRead", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllAsRead indicates an expected call of MarkAllAsRead.
func (mr *MockNotificationInterfaceMockRecorder) MarkAllAsRead(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllAsRead", reflect.TypeOf((*MockNotificationInterface)(nil).MarkAllAsRead), ctx, userId)
}

// MarkAsRead mocks base method.
func (m *MockNotificationInterface) MarkAsRead(ctx context.Context, userId, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, userId, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockNotificationInterfaceMockRecorder) MarkAsRead(ctx, userId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockNotificationInterface)(nil).MarkAsRead), ctx, userId, id)
}
