// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/oldest_record.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/oldest_record.go -destination=./internal/mock/mock_usecase/oldest_record.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOldestRecordInterface is a mock of OldestRecordInterface interface.
type MockOldestRecordInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOldestRecordInterfaceMockRecorder
	isgomock struct{}
}

// MockOldestRecordInterfaceMockRecorder is the mock recorder for MockOldestRecordInterface.
type MockOldestRecordInterfaceMockRecorder struct {
	mock *MockOldestRecordInterface
}

// NewMockOldestRecordInterface creates a new mock instance.
func NewMockOldestRecordInterface(ctrl *gomock.Controller) *MockOldestRecordInterface {
	mock := &MockOldestRecordInterface{ctrl: ctrl}
	mock.recorder = &MockOldestRecordInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOldestRecordInterface) EXPECT() *MockOldestRecordInterfaceMockRecorder {
	return m.recorder
}

// GetOldestRecord mocks base method.
func (m *MockOldestRecordInterface) GetOldestRecord(ctx context.Context, userId, deckId string) (*entity.OldestRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOldestRecord", ctx, userId, deckId)
	ret0, _ := ret[0].(*entity.OldestRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOldestRecord indicates an expected call of GetOldestRecord.
func (mr *MockOldestRecordInterfaceMockRecorder) GetOldestRecord(ctx, userId, deckId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOldestRecord", reflect.TypeOf((*MockOldestRecordInterface)(nil).GetOldestRecord), ctx, userId, deckId)
}
