// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/opponent_deck_candidate.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/opponent_deck_candidate.go -destination=./internal/mock/mock_usecase/opponent_deck_candidate.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOpponentDeckCandidateInterface is a mock of OpponentDeckCandidateInterface interface.
type MockOpponentDeckCandidateInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOpponentDeckCandidateInterfaceMockRecorder
	isgomock struct{}
}

// MockOpponentDeckCandidateInterfaceMockRecorder is the mock recorder for MockOpponentDeckCandidateInterface.
type MockOpponentDeckCandidateInterfaceMockRecorder struct {
	mock *MockOpponentDeckCandidateInterface
}

// NewMockOpponentDeckCandidateInterface creates a new mock instance.
func NewMockOpponentDeckCandidateInterface(ctrl *gomock.Controller) *MockOpponentDeckCandidateInterface {
	mock := &MockOpponentDeckCandidateInterface{ctrl: ctrl}
	mock.recorder = &MockOpponentDeckCandidateInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpponentDeckCandidateInterface) EXPECT() *MockOpponentDeckCandidateInterfaceMockRecorder {
	return m.recorder
}

// FindOpponentDeckCandidates mocks base method.
func (m *MockOpponentDeckCandidateInterface) FindOpponentDeckCandidates(ctx context.Context, limit int) ([]*entity.OpponentDeckCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOpponentDeckCandidates", ctx, limit)
	ret0, _ := ret[0].([]*entity.OpponentDeckCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOpponentDeckCandidates indicates an expected call of FindOpponentDeckCandidates.
func (mr *MockOpponentDeckCandidateInterfaceMockRecorder) FindOpponentDeckCandidates(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOpponentDeckCandidates", reflect.TypeOf((*MockOpponentDeckCandidateInterface)(nil).FindOpponentDeckCandidates), ctx, limit)
}
