// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/opponent_deck.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/opponent_deck.go -destination=./internal/mock/mock_usecase/opponent_deck.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	usecase "github.com/vsrecorder/core-apiserver/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockOpponentDeckInterface is a mock of OpponentDeckInterface interface.
type MockOpponentDeckInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOpponentDeckInterfaceMockRecorder
	isgomock struct{}
}

// MockOpponentDeckInterfaceMockRecorder is the mock recorder for MockOpponentDeckInterface.
type MockOpponentDeckInterfaceMockRecorder struct {
	mock *MockOpponentDeckInterface
}

// NewMockOpponentDeckInterface creates a new mock instance.
func NewMockOpponentDeckInterface(ctrl *gomock.Controller) *MockOpponentDeckInterface {
	mock := &MockOpponentDeckInterface{ctrl: ctrl}
	mock.recorder = &MockOpponentDeckInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpponentDeckInterface) EXPECT() *MockOpponentDeckInterfaceMockRecorder {
	return m.recorder
}

// FindByUserId mocks base method.
func (m *MockOpponentDeckInterface) FindByUserId(ctx context.Context, uid string) ([]*entity.OpponentDeck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, uid)
	ret0, _ := ret[0].([]*entity.OpponentDeck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockOpponentDeckInterfaceMockRecorder) FindByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockOpponentDeckInterface)(nil).FindByUserId), ctx, uid)
}

// Replace mocks base method.
func (m *MockOpponentDeckInterface) Replace(ctx context.Context, uid string, param *usecase.OpponentDeckReplaceParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, uid, param)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockOpponentDeckInterfaceMockRecorder) Replace(ctx, uid, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockOpponentDeckInterface)(nil).Replace), ctx, uid, param)
}
