// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/opponent_deck_usage_stat.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/opponent_deck_usage_stat.go -destination=./internal/mock/mock_usecase/opponent_deck_usage_stat.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOpponentDeckUsageStatInterface is a mock of OpponentDeckUsageStatInterface interface.
type MockOpponentDeckUsageStatInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOpponentDeckUsageStatInterfaceMockRecorder
	isgomock struct{}
}

// MockOpponentDeckUsageStatInterfaceMockRecorder is the mock recorder for MockOpponentDeckUsageStatInterface.
type MockOpponentDeckUsageStatInterfaceMockRecorder struct {
	mock *MockOpponentDeckUsageStatInterface
}

// NewMockOpponentDeckUsageStatInterface creates a new mock instance.
func NewMockOpponentDeckUsageStatInterface(ctrl *gomock.Controller) *MockOpponentDeckUsageStatInterface {
	mock := &MockOpponentDeckUsageStatInterface{ctrl: ctrl}
	mock.recorder = &MockOpponentDeckUsageStatInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpponentDeckUsageStatInterface) EXPECT() *MockOpponentDeckUsageStatInterfaceMockRecorder {
	return m.recorder
}

// GetOpponentDeckUsageStat mocks base method.
func (m *MockOpponentDeckUsageStatInterface) GetOpponentDeckUsageStat(ctx context.Context, userId, yearMonth, environmentId, season, deckId string) (*entity.OpponentDeckUsageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpponentDeckUsageStat", ctx, userId, yearMonth, environmentId, season, deckId)
	ret0, _ := ret[0].(*entity.OpponentDeckUsageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpponentDeckUsageStat indicates an expected call of GetOpponentDeckUsageStat.
func (mr *MockOpponentDeckUsageStatInterfaceMockRecorder) GetOpponentDeckUsageStat(ctx, userId, yearMonth, environmentId, season, deckId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpponentDeckUsageStat", reflect.TypeOf((*MockOpponentDeckUsageStatInterface)(nil).GetOpponentDeckUsageStat), ctx, userId, yearMonth, environmentId, season, deckId)
}
