// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/push_notifier.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/push_notifier.go -destination=./internal/mock/mock_usecase/push_notifier.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPushNotifierInterface is a mock of PushNotifierInterface interface.
type MockPushNotifierInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPushNotifierInterfaceMockRecorder
	isgomock struct{}
}

// MockPushNotifierInterfaceMockRecorder is the mock recorder for MockPushNotifierInterface.
type MockPushNotifierInterfaceMockRecorder struct {
	mock *MockPushNotifierInterface
}

// NewMockPushNotifierInterface creates a new mock instance.
func NewMockPushNotifierInterface(ctrl *gomock.Controller) *MockPushNotifierInterface {
	mock := &MockPushNotifierInterface{ctrl: ctrl}
	mock.recorder = &MockPushNotifierInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushNotifierInterface) EXPECT() *MockPushNotifierInterfaceMockRecorder {
	return m.recorder
}

// Deliver mocks base method.
func (m *MockPushNotifierInterface) Deliver(ctx context.Context, notification *entity.Notification, campaign string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deliver", ctx, notification, campaign)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deliver indicates an expected call of Deliver.
func (mr *MockPushNotifierInterfaceMockRecorder) Deliver(ctx, notification, campaign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deliver", reflect.TypeOf((*MockPushNotifierInterface)(nil).Deliver), ctx, notification, campaign)
}
