// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/push_delivery.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/push_delivery.go -destination=./internal/mock/mock_usecase/push_delivery.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPushDeliveryInterface is a mock of PushDeliveryInterface interface.
type MockPushDeliveryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPushDeliveryInterfaceMockRecorder
	isgomock struct{}
}

// MockPushDeliveryInterfaceMockRecorder is the mock recorder for MockPushDeliveryInterface.
type MockPushDeliveryInterfaceMockRecorder struct {
	mock *MockPushDeliveryInterface
}

// NewMockPushDeliveryInterface creates a new mock instance.
func NewMockPushDeliveryInterface(ctrl *gomock.Controller) *MockPushDeliveryInterface {
	mock := &MockPushDeliveryInterface{ctrl: ctrl}
	mock.recorder = &MockPushDeliveryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushDeliveryInterface) EXPECT() *MockPushDeliveryInterfaceMockRecorder {
	return m.recorder
}

// MarkClicked mocks base method.
func (m *MockPushDeliveryInterface) MarkClicked(ctx context.Context, userId, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkClicked", ctx, userId, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkClicked indicates an expected call of MarkClicked.
func (mr *MockPushDeliveryInterfaceMockRecorder) MarkClicked(ctx, userId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkClicked", reflect.TypeOf((*MockPushDeliveryInterface)(nil).MarkClicked), ctx, userId, id)
}

// MarkDelivered mocks base method.
func (m *MockPushDeliveryInterface) MarkDelivered(ctx context.Context, userId, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDelivered", ctx, userId, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDelivered indicates an expected call of MarkDelivered.
func (mr *MockPushDeliveryInterfaceMockRecorder) MarkDelivered(ctx, userId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDelivered", reflect.TypeOf((*MockPushDeliveryInterface)(nil).MarkDelivered), ctx, userId, id)
}
