// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/push_subscription.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/push_subscription.go -destination=./internal/mock/mock_usecase/push_subscription.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPushSubscriptionInterface is a mock of PushSubscriptionInterface interface.
type MockPushSubscriptionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPushSubscriptionInterfaceMockRecorder
	isgomock struct{}
}

// MockPushSubscriptionInterfaceMockRecorder is the mock recorder for MockPushSubscriptionInterface.
type MockPushSubscriptionInterfaceMockRecorder struct {
	mock *MockPushSubscriptionInterface
}

// NewMockPushSubscriptionInterface creates a new mock instance.
func NewMockPushSubscriptionInterface(ctrl *gomock.Controller) *MockPushSubscriptionInterface {
	mock := &MockPushSubscriptionInterface{ctrl: ctrl}
	mock.recorder = &MockPushSubscriptionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushSubscriptionInterface) EXPECT() *MockPushSubscriptionInterfaceMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockPushSubscriptionInterface) Subscribe(ctx context.Context, userId, endpoint, p256dh, auth, platform string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, userId, endpoint, p256dh, auth, platform)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockPushSubscriptionInterfaceMockRecorder) Subscribe(ctx, userId, endpoint, p256dh, auth, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockPushSubscriptionInterface)(nil).Subscribe), ctx, userId, endpoint, p256dh, auth, platform)
}

// Unsubscribe mocks base method.
func (m *MockPushSubscriptionInterface) Unsubscribe(ctx context.Context, userId, endpoint string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, userId, endpoint)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockPushSubscriptionInterfaceMockRecorder) Unsubscribe(ctx, userId, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockPushSubscriptionInterface)(nil).Unsubscribe), ctx, userId, endpoint)
}
