// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/shop.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/shop.go -destination=./internal/mock/mock_usecase/shop.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockShopInterface is a mock of ShopInterface interface.
type MockShopInterface struct {
	ctrl     *gomock.Controller
	recorder *MockShopInterfaceMockRecorder
	isgomock struct{}
}

// MockShopInterfaceMockRecorder is the mock recorder for MockShopInterface.
type MockShopInterfaceMockRecorder struct {
	mock *MockShopInterface
}

// NewMockShopInterface creates a new mock instance.
func NewMockShopInterface(ctrl *gomock.Controller) *MockShopInterface {
	mock := &MockShopInterface{ctrl: ctrl}
	mock.recorder = &MockShopInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopInterface) EXPECT() *MockShopInterfaceMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockShopInterface) Find(ctx context.Context, keyword string, limit int) ([]*entity.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, keyword, limit)
	ret0, _ := ret[0].([]*entity.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockShopInterfaceMockRecorder) Find(ctx, keyword, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockShopInterface)(nil).Find), ctx, keyword, limit)
}
