// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/standard_regulation.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/standard_regulation.go -destination=./internal/mock/mock_usecase/standard_regulation.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockStandardRegulationInterface is a mock of StandardRegulationInterface interface.
type MockStandardRegulationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStandardRegulationInterfaceMockRecorder
	isgomock struct{}
}

// MockStandardRegulationInterfaceMockRecorder is the mock recorder for MockStandardRegulationInterface.
type MockStandardRegulationInterfaceMockRecorder struct {
	mock *MockStandardRegulationInterface
}

// NewMockStandardRegulationInterface creates a new mock instance.
func NewMockStandardRegulationInterface(ctrl *gomock.Controller) *MockStandardRegulationInterface {
	mock := &MockStandardRegulationInterface{ctrl: ctrl}
	mock.recorder = &MockStandardRegulationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStandardRegulationInterface) EXPECT() *MockStandardRegulationInterfaceMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockStandardRegulationInterface) Find(ctx context.Context) ([]*entity.StandardRegulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]*entity.StandardRegulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockStandardRegulationInterfaceMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStandardRegulationInterface)(nil).Find), ctx)
}

// FindByDate mocks base method.
func (m *MockStandardRegulationInterface) FindByDate(ctx context.Context, date time.Time) (*entity.StandardRegulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDate", ctx, date)
	ret0, _ := ret[0].(*entity.StandardRegulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDate indicates an expected call of FindByDate.
func (mr *MockStandardRegulationInterfaceMockRecorder) FindByDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDate", reflect.TypeOf((*MockStandardRegulationInterface)(nil).FindByDate), ctx, date)
}

// FindById mocks base method.
func (m *MockStandardRegulationInterface) FindById(ctx context.Context, id string) (*entity.StandardRegulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*entity.StandardRegulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockStandardRegulationInterfaceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockStandardRegulationInterface)(nil).FindById), ctx, id)
}
