// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/streak.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/streak.go -destination=./internal/mock/mock_usecase/streak.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockStreakInterface is a mock of StreakInterface interface.
type MockStreakInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStreakInterfaceMockRecorder
	isgomock struct{}
}

// MockStreakInterfaceMockRecorder is the mock recorder for MockStreakInterface.
type MockStreakInterfaceMockRecorder struct {
	mock *MockStreakInterface
}

// NewMockStreakInterface creates a new mock instance.
func NewMockStreakInterface(ctrl *gomock.Controller) *MockStreakInterface {
	mock := &MockStreakInterface{ctrl: ctrl}
	mock.recorder = &MockStreakInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreakInterface) EXPECT() *MockStreakInterfaceMockRecorder {
	return m.recorder
}

// GetByUserId mocks base method.
func (m *MockStreakInterface) GetByUserId(ctx context.Context, userId string) (*entity.UserStreak, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserId", ctx, userId)
	ret0, _ := ret[0].(*entity.UserStreak)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserId indicates an expected call of GetByUserId.
func (mr *MockStreakInterfaceMockRecorder) GetByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserId", reflect.TypeOf((*MockStreakInterface)(nil).GetByUserId), ctx, userId)
}
