// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/tag.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/tag.go -destination=./internal/mock/mock_usecase/tag.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	usecase "github.com/vsrecorder/core-apiserver/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockTagInterface is a mock of TagInterface interface.
type MockTagInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTagInterfaceMockRecorder
	isgomock struct{}
}

// MockTagInterfaceMockRecorder is the mock recorder for MockTagInterface.
type MockTagInterfaceMockRecorder struct {
	mock *MockTagInterface
}

// NewMockTagInterface creates a new mock instance.
func NewMockTagInterface(ctrl *gomock.Controller) *MockTagInterface {
	mock := &MockTagInterface{ctrl: ctrl}
	mock.recorder = &MockTagInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagInterface) EXPECT() *MockTagInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTagInterface) Create(ctx context.Context, param *usecase.TagCreateParam) (*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, param)
	ret0, _ := ret[0].(*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTagInterfaceMockRecorder) Create(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagInterface)(nil).Create), ctx, param)
}

// Delete mocks base method.
func (m *MockTagInterface) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTagInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagInterface)(nil).Delete), ctx, id)
}

// FindByUserId mocks base method.
func (m *MockTagInterface) FindByUserId(ctx context.Context, uid string) ([]*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, uid)
	ret0, _ := ret[0].([]*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockTagInterfaceMockRecorder) FindByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockTagInterface)(nil).FindByUserId), ctx, uid)
}

// FindPresets mocks base method.
func (m *MockTagInterface) FindPresets(ctx context.Context) ([]*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPresets", ctx)
	ret0, _ := ret[0].([]*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPresets indicates an expected call of FindPresets.
func (mr *MockTagInterfaceMockRecorder) FindPresets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPresets", reflect.TypeOf((*MockTagInterface)(nil).FindPresets), ctx)
}

// Update mocks base method.
func (m *MockTagInterface) Update(ctx context.Context, id string, param *usecase.TagUpdateParam) (*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, param)
	ret0, _ := ret[0].(*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTagInterfaceMockRecorder) Update(ctx, id, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTagInterface)(nil).Update), ctx, id, param)
}
