// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/unofficial_event.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/unofficial_event.go -destination=./internal/mock/mock_usecase/unofficial_event.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	usecase "github.com/vsrecorder/core-apiserver/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUnofficialEventInterface is a mock of UnofficialEventInterface interface.
type MockUnofficialEventInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUnofficialEventInterfaceMockRecorder
	isgomock struct{}
}

// MockUnofficialEventInterfaceMockRecorder is the mock recorder for MockUnofficialEventInterface.
type MockUnofficialEventInterfaceMockRecorder struct {
	mock *MockUnofficialEventInterface
}

// NewMockUnofficialEventInterface creates a new mock instance.
func NewMockUnofficialEventInterface(ctrl *gomock.Controller) *MockUnofficialEventInterface {
	mock := &MockUnofficialEventInterface{ctrl: ctrl}
	mock.recorder = &MockUnofficialEventInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnofficialEventInterface) EXPECT() *MockUnofficialEventInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUnofficialEventInterface) Create(ctx context.Context, param *usecase.UnofficialEventParam) (*entity.UnofficialEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, param)
	ret0, _ := ret[0].(*entity.UnofficialEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUnofficialEventInterfaceMockRecorder) Create(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUnofficialEventInterface)(nil).Create), ctx, param)
}

// FindById mocks base method.
func (m *MockUnofficialEventInterface) FindById(ctx context.Context, id string) (*entity.UnofficialEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*entity.UnofficialEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockUnofficialEventInterfaceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockUnofficialEventInterface)(nil).FindById), ctx, id)
}
