// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/user_player.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/user_player.go -destination=./internal/mock/mock_usecase/user_player.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	usecase "github.com/vsrecorder/core-apiserver/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUserPlayerInterface is a mock of UserPlayerInterface interface.
type MockUserPlayerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserPlayerInterfaceMockRecorder
	isgomock struct{}
}

// MockUserPlayerInterfaceMockRecorder is the mock recorder for MockUserPlayerInterface.
type MockUserPlayerInterfaceMockRecorder struct {
	mock *MockUserPlayerInterface
}

// NewMockUserPlayerInterface creates a new mock instance.
func NewMockUserPlayerInterface(ctrl *gomock.Controller) *MockUserPlayerInterface {
	mock := &MockUserPlayerInterface{ctrl: ctrl}
	mock.recorder = &MockUserPlayerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPlayerInterface) EXPECT() *MockUserPlayerInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserPlayerInterface) Create(ctx context.Context, param *usecase.UserPlayerCreateParam) (*entity.UserPlayer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, param)
	ret0, _ := ret[0].(*entity.UserPlayer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserPlayerInterfaceMockRecorder) Create(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserPlayerInterface)(nil).Create), ctx, param)
}

// FindByUserId mocks base method.
func (m *MockUserPlayerInterface) FindByUserId(ctx context.Context, userId string) (*entity.UserPlayer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, userId)
	ret0, _ := ret[0].(*entity.UserPlayer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockUserPlayerInterfaceMockRecorder) FindByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockUserPlayerInterface)(nil).FindByUserId), ctx, userId)
}

// FindCityleagueResultsByUserId mocks base method.
func (m *MockUserPlayerInterface) FindCityleagueResultsByUserId(ctx context.Context, userId, season string) ([]*entity.PlayerCityleagueResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCityleagueResultsByUserId", ctx, userId, season)
	ret0, _ := ret[0].([]*entity.PlayerCityleagueResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCityleagueResultsByUserId indicates an expected call of FindCityleagueResultsByUserId.
func (mr *MockUserPlayerInterfaceMockRecorder) FindCityleagueResultsByUserId(ctx, userId, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCityleagueResultsByUserId", reflect.TypeOf((*MockUserPlayerInterface)(nil).FindCityleagueResultsByUserId), ctx, userId, season)
}
