// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/user_acquisition.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/user_acquisition.go -destination=./internal/mock/mock_usecase/user_acquisition.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	usecase "github.com/vsrecorder/core-apiserver/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUserAcquisitionInterface is a mock of UserAcquisitionInterface interface.
type MockUserAcquisitionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserAcquisitionInterfaceMockRecorder
	isgomock struct{}
}

// MockUserAcquisitionInterfaceMockRecorder is the mock recorder for MockUserAcquisitionInterface.
type MockUserAcquisitionInterfaceMockRecorder struct {
	mock *MockUserAcquisitionInterface
}

// NewMockUserAcquisitionInterface creates a new mock instance.
func NewMockUserAcquisitionInterface(ctrl *gomock.Controller) *MockUserAcquisitionInterface {
	mock := &MockUserAcquisitionInterface{ctrl: ctrl}
	mock.recorder = &MockUserAcquisitionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAcquisitionInterface) EXPECT() *MockUserAcquisitionInterfaceMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockUserAcquisitionInterface) Record(ctx context.Context, userId string, param *usecase.UserAcquisitionRecordParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", ctx, userId, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockUserAcquisitionInterfaceMockRecorder) Record(ctx, userId, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockUserAcquisitionInterface)(nil).Record), ctx, userId, param)
}
