// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/user_stat.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/user_stat.go -destination=./internal/mock/mock_usecase/user_stat.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStatInterface is a mock of UserStatInterface interface.
type MockUserStatInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserStatInterfaceMockRecorder
	isgomock struct{}
}

// MockUserStatInterfaceMockRecorder is the mock recorder for MockUserStatInterface.
type MockUserStatInterfaceMockRecorder struct {
	mock *MockUserStatInterface
}

// NewMockUserStatInterface creates a new mock instance.
func NewMockUserStatInterface(ctrl *gomock.Controller) *MockUserStatInterface {
	mock := &MockUserStatInterface{ctrl: ctrl}
	mock.recorder = &MockUserStatInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStatInterface) EXPECT() *MockUserStatInterfaceMockRecorder {
	return m.recorder
}

// GetUserStat mocks base method.
func (m *MockUserStatInterface) GetUserStat(ctx context.Context, userId, yearMonth, environmentId, season string) (*entity.UserStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStat", ctx, userId, yearMonth, environmentId, season)
	ret0, _ := ret[0].(*entity.UserStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStat indicates an expected call of GetUserStat.
func (mr *MockUserStatInterfaceMockRecorder) GetUserStat(ctx, userId, yearMonth, environmentId, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStat", reflect.TypeOf((*MockUserStatInterface)(nil).GetUserStat), ctx, userId, yearMonth, environmentId, season)
}
