// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/user_stat_history.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/user_stat_history.go -destination=./internal/mock/mock_usecase/user_stat_history.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStatHistoryInterface is a mock of UserStatHistoryInterface interface.
type MockUserStatHistoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserStatHistoryInterfaceMockRecorder
	isgomock struct{}
}

// MockUserStatHistoryInterfaceMockRecorder is the mock recorder for MockUserStatHistoryInterface.
type MockUserStatHistoryInterfaceMockRecorder struct {
	mock *MockUserStatHistoryInterface
}

// NewMockUserStatHistoryInterface creates a new mock instance.
func NewMockUserStatHistoryInterface(ctrl *gomock.Controller) *MockUserStatHistoryInterface {
	mock := &MockUserStatHistoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserStatHistoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStatHistoryInterface) EXPECT() *MockUserStatHistoryInterfaceMockRecorder {
	return m.recorder
}

// GetUserStatHistory mocks base method.
func (m *MockUserStatHistoryInterface) GetUserStatHistory(ctx context.Context, userId, period, season string) ([]*entity.UserStatMonthly, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStatHistory", ctx, userId, period, season)
	ret0, _ := ret[0].([]*entity.UserStatMonthly)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStatHistory indicates an expected call of GetUserStatHistory.
func (mr *MockUserStatHistoryInterfaceMockRecorder) GetUserStatHistory(ctx, userId, period, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStatHistory", reflect.TypeOf((*MockUserStatHistoryInterface)(nil).GetUserStatHistory), ctx, userId, period, season)
}
