// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/user_daily_activity.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/user_daily_activity.go -destination=./internal/mock/mock_usecase/user_daily_activity.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserDailyActivityInterface is a mock of UserDailyActivityInterface interface.
type MockUserDailyActivityInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserDailyActivityInterfaceMockRecorder
	isgomock struct{}
}

// MockUserDailyActivityInterfaceMockRecorder is the mock recorder for MockUserDailyActivityInterface.
type MockUserDailyActivityInterfaceMockRecorder struct {
	mock *MockUserDailyActivityInterface
}

// NewMockUserDailyActivityInterface creates a new mock instance.
func NewMockUserDailyActivityInterface(ctrl *gomock.Controller) *MockUserDailyActivityInterface {
	mock := &MockUserDailyActivityInterface{ctrl: ctrl}
	mock.recorder = &MockUserDailyActivityInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDailyActivityInterface) EXPECT() *MockUserDailyActivityInterfaceMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockUserDailyActivityInterface) Record(ctx context.Context, userId string, categories []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", ctx, userId, categories)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockUserDailyActivityInterfaceMockRecorder) Record(ctx, userId, categories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockUserDailyActivityInterface)(nil).Record), ctx, userId, categories)
}
