// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/user_stat_recent.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/user_stat_recent.go -destination=./internal/mock/mock_usecase/user_stat_recent.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStatRecentInterface is a mock of UserStatRecentInterface interface.
type MockUserStatRecentInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserStatRecentInterfaceMockRecorder
	isgomock struct{}
}

// MockUserStatRecentInterfaceMockRecorder is the mock recorder for MockUserStatRecentInterface.
type MockUserStatRecentInterfaceMockRecorder struct {
	mock *MockUserStatRecentInterface
}

// NewMockUserStatRecentInterface creates a new mock instance.
func NewMockUserStatRecentInterface(ctrl *gomock.Controller) *MockUserStatRecentInterface {
	mock := &MockUserStatRecentInterface{ctrl: ctrl}
	mock.recorder = &MockUserStatRecentInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStatRecentInterface) EXPECT() *MockUserStatRecentInterfaceMockRecorder {
	return m.recorder
}

// GetRecentMatches mocks base method.
func (m *MockUserStatRecentInterface) GetRecentMatches(ctx context.Context, userId string, count int, deckId string) (*entity.RecentMatchStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentMatches", ctx, userId, count, deckId)
	ret0, _ := ret[0].(*entity.RecentMatchStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentMatches indicates an expected call of GetRecentMatches.
func (mr *MockUserStatRecentInterfaceMockRecorder) GetRecentMatches(ctx, userId, count, deckId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentMatches", reflect.TypeOf((*MockUserStatRecentInterface)(nil).GetRecentMatches), ctx, userId, count, deckId)
}
