// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/user_gym.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/user_gym.go -destination=./internal/mock/mock_usecase/user_gym.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserGymInterface is a mock of UserGymInterface interface.
type MockUserGymInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserGymInterfaceMockRecorder
	isgomock struct{}
}

// MockUserGymInterfaceMockRecorder is the mock recorder for MockUserGymInterface.
type MockUserGymInterfaceMockRecorder struct {
	mock *MockUserGymInterface
}

// NewMockUserGymInterface creates a new mock instance.
func NewMockUserGymInterface(ctrl *gomock.Controller) *MockUserGymInterface {
	mock := &MockUserGymInterface{ctrl: ctrl}
	mock.recorder = &MockUserGymInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserGymInterface) EXPECT() *MockUserGymInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserGymInterface) Create(ctx context.Context, uid string, shopId uint) (*entity.UserGymView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, uid, shopId)
	ret0, _ := ret[0].(*entity.UserGymView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserGymInterfaceMockRecorder) Create(ctx, uid, shopId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserGymInterface)(nil).Create), ctx, uid, shopId)
}

// Delete mocks base method.
func (m *MockUserGymInterface) Delete(ctx context.Context, uid string, shopId uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uid, shopId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserGymInterfaceMockRecorder) Delete(ctx, uid, shopId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserGymInterface)(nil).Delete), ctx, uid, shopId)
}

// Find mocks base method.
func (m *MockUserGymInterface) Find(ctx context.Context, uid string) ([]*entity.UserGymView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, uid)
	ret0, _ := ret[0].([]*entity.UserGymView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserGymInterfaceMockRecorder) Find(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserGymInterface)(nil).Find), ctx, uid)
}

// FindOfficialEvents mocks base method.
func (m *MockUserGymInterface) FindOfficialEvents(ctx context.Context, uid string, startDate, endDate time.Time) ([]*entity.UserGymView, []*entity.OfficialEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOfficialEvents", ctx, uid, startDate, endDate)
	ret0, _ := ret[0].([]*entity.UserGymView)
	ret1, _ := ret[1].([]*entity.OfficialEvent)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindOfficialEvents indicates an expected call of FindOfficialEvents.
func (mr *MockUserGymInterfaceMockRecorder) FindOfficialEvents(ctx, uid, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOfficialEvents", reflect.TypeOf((*MockUserGymInterface)(nil).FindOfficialEvents), ctx, uid, startDate, endDate)
}
