// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/weekly_deck_usage_stat.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/weekly_deck_usage_stat.go -destination=./internal/mock/mock_usecase/weekly_deck_usage_stat.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockWeeklyDeckUsageStatInterface is a mock of WeeklyDeckUsageStatInterface interface.
type MockWeeklyDeckUsageStatInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWeeklyDeckUsageStatInterfaceMockRecorder
	isgomock struct{}
}

// MockWeeklyDeckUsageStatInterfaceMockRecorder is the mock recorder for MockWeeklyDeckUsageStatInterface.
type MockWeeklyDeckUsageStatInterfaceMockRecorder struct {
	mock *MockWeeklyDeckUsageStatInterface
}

// NewMockWeeklyDeckUsageStatInterface creates a new mock instance.
func NewMockWeeklyDeckUsageStatInterface(ctrl *gomock.Controller) *MockWeeklyDeckUsageStatInterface {
	mock := &MockWeeklyDeckUsageStatInterface{ctrl: ctrl}
	mock.recorder = &MockWeeklyDeckUsageStatInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeeklyDeckUsageStatInterface) EXPECT() *MockWeeklyDeckUsageStatInterfaceMockRecorder {
	return m.recorder
}

// GetWeeklyDeckUsageStat mocks base method.
func (m *MockWeeklyDeckUsageStatInterface) GetWeeklyDeckUsageStat(ctx context.Context, week string) (*entity.WeeklyDeckUsageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeeklyDeckUsageStat", ctx, week)
	ret0, _ := ret[0].(*entity.WeeklyDeckUsageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeeklyDeckUsageStat indicates an expected call of GetWeeklyDeckUsageStat.
func (mr *MockWeeklyDeckUsageStatInterfaceMockRecorder) GetWeeklyDeckUsageStat(ctx, week any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeeklyDeckUsageStat", reflect.TypeOf((*MockWeeklyDeckUsageStatInterface)(nil).GetWeeklyDeckUsageStat), ctx, week)
}
