// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/badge_definition.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/badge_definition.go -destination=./internal/mock/mock_repository/badge_definition.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockBadgeDefinitionInterface is a mock of BadgeDefinitionInterface interface.
type MockBadgeDefinitionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBadgeDefinitionInterfaceMockRecorder
	isgomock struct{}
}

// MockBadgeDefinitionInterfaceMockRecorder is the mock recorder for MockBadgeDefinitionInterface.
type MockBadgeDefinitionInterfaceMockRecorder struct {
	mock *MockBadgeDefinitionInterface
}

// NewMockBadgeDefinitionInterface creates a new mock instance.
func NewMockBadgeDefinitionInterface(ctrl *gomock.Controller) *MockBadgeDefinitionInterface {
	mock := &MockBadgeDefinitionInterface{ctrl: ctrl}
	mock.recorder = &MockBadgeDefinitionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBadgeDefinitionInterface) EXPECT() *MockBadgeDefinitionInterfaceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockBadgeDefinitionInterface) FindAll(ctx context.Context) ([]*entity.BadgeDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*entity.BadgeDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBadgeDefinitionInterfaceMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBadgeDefinitionInterface)(nil).FindAll), ctx)
}
