// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/badge_stats.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/badge_stats.go -destination=./internal/mock/mock_repository/badge_stats.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockBadgeStatsInterface is a mock of BadgeStatsInterface interface.
type MockBadgeStatsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBadgeStatsInterfaceMockRecorder
	isgomock struct{}
}

// MockBadgeStatsInterfaceMockRecorder is the mock recorder for MockBadgeStatsInterface.
type MockBadgeStatsInterfaceMockRecorder struct {
	mock *MockBadgeStatsInterface
}

// NewMockBadgeStatsInterface creates a new mock instance.
func NewMockBadgeStatsInterface(ctrl *gomock.Controller) *MockBadgeStatsInterface {
	mock := &MockBadgeStatsInterface{ctrl: ctrl}
	mock.recorder = &MockBadgeStatsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBadgeStatsInterface) EXPECT() *MockBadgeStatsInterfaceMockRecorder {
	return m.recorder
}

// CountDecksByUserId mocks base method.
func (m *MockBadgeStatsInterface) CountDecksByUserId(ctx context.Context, userId string, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDecksByUserId", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDecksByUserId indicates an expected call of CountDecksByUserId.
func (mr *MockBadgeStatsInterfaceMockRecorder) CountDecksByUserId(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDecksByUserId", reflect.TypeOf((*MockBadgeStatsInterface)(nil).CountDecksByUserId), ctx, userId, fromDate, toDate)
}

// CountMatchesByUserId mocks base method.
func (m *MockBadgeStatsInterface) CountMatchesByUserId(ctx context.Context, userId string, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMatchesByUserId", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMatchesByUserId indicates an expected call of CountMatchesByUserId.
func (mr *MockBadgeStatsInterfaceMockRecorder) CountMatchesByUserId(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMatchesByUserId", reflect.TypeOf((*MockBadgeStatsInterface)(nil).CountMatchesByUserId), ctx, userId, fromDate, toDate)
}

// CountRecordsByUserId mocks base method.
func (m *MockBadgeStatsInterface) CountRecordsByUserId(ctx context.Context, userId string, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecordsByUserId", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecordsByUserId indicates an expected call of CountRecordsByUserId.
func (mr *MockBadgeStatsInterfaceMockRecorder) CountRecordsByUserId(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecordsByUserId", reflect.TypeOf((*MockBadgeStatsInterface)(nil).CountRecordsByUserId), ctx, userId, fromDate, toDate)
}

// FindRecordDatesByUserId mocks base method.
func (m *MockBadgeStatsInterface) FindRecordDatesByUserId(ctx context.Context, userId string, fromDate, toDate time.Time) ([]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRecordDatesByUserId", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].([]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRecordDatesByUserId indicates an expected call of FindRecordDatesByUserId.
func (mr *MockBadgeStatsInterfaceMockRecorder) FindRecordDatesByUserId(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRecordDatesByUserId", reflect.TypeOf((*MockBadgeStatsInterface)(nil).FindRecordDatesByUserId), ctx, userId, fromDate, toDate)
}
