// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/championsleague_schedule.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/championsleague_schedule.go -destination=./internal/mock/mock_repository/championsleague_schedule.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockChampionsleagueScheduleInterface is a mock of ChampionsleagueScheduleInterface interface.
type MockChampionsleagueScheduleInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChampionsleagueScheduleInterfaceMockRecorder
	isgomock struct{}
}

// MockChampionsleagueScheduleInterfaceMockRecorder is the mock recorder for MockChampionsleagueScheduleInterface.
type MockChampionsleagueScheduleInterfaceMockRecorder struct {
	mock *MockChampionsleagueScheduleInterface
}

// NewMockChampionsleagueScheduleInterface creates a new mock instance.
func NewMockChampionsleagueScheduleInterface(ctrl *gomock.Controller) *MockChampionsleagueScheduleInterface {
	mock := &MockChampionsleagueScheduleInterface{ctrl: ctrl}
	mock.recorder = &MockChampionsleagueScheduleInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChampionsleagueScheduleInterface) EXPECT() *MockChampionsleagueScheduleInterfaceMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockChampionsleagueScheduleInterface) Find(ctx context.Context) ([]*entity.ChampionsleagueSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]*entity.ChampionsleagueSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockChampionsleagueScheduleInterfaceMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockChampionsleagueScheduleInterface)(nil).Find), ctx)
}

// FindById mocks base method.
func (m *MockChampionsleagueScheduleInterface) FindById(ctx context.Context, id string) (*entity.ChampionsleagueSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*entity.ChampionsleagueSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockChampionsleagueScheduleInterfaceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockChampionsleagueScheduleInterface)(nil).FindById), ctx, id)
}
