// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/championship_series.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/championship_series.go -destination=./internal/mock/mock_repository/championship_series.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockChampionshipSeriesInterface is a mock of ChampionshipSeriesInterface interface.
type MockChampionshipSeriesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChampionshipSeriesInterfaceMockRecorder
	isgomock struct{}
}

// MockChampionshipSeriesInterfaceMockRecorder is the mock recorder for MockChampionshipSeriesInterface.
type MockChampionshipSeriesInterfaceMockRecorder struct {
	mock *MockChampionshipSeriesInterface
}

// NewMockChampionshipSeriesInterface creates a new mock instance.
func NewMockChampionshipSeriesInterface(ctrl *gomock.Controller) *MockChampionshipSeriesInterface {
	mock := &MockChampionshipSeriesInterface{ctrl: ctrl}
	mock.recorder = &MockChampionshipSeriesInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChampionshipSeriesInterface) EXPECT() *MockChampionshipSeriesInterfaceMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockChampionshipSeriesInterface) Find(ctx context.Context) ([]*entity.ChampionshipSeries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]*entity.ChampionshipSeries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockChampionshipSeriesInterfaceMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockChampionshipSeriesInterface)(nil).Find), ctx)
}

// FindByDate mocks base method.
func (m *MockChampionshipSeriesInterface) FindByDate(ctx context.Context, date time.Time) (*entity.ChampionshipSeries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDate", ctx, date)
	ret0, _ := ret[0].(*entity.ChampionshipSeries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDate indicates an expected call of FindByDate.
func (mr *MockChampionshipSeriesInterfaceMockRecorder) FindByDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDate", reflect.TypeOf((*MockChampionshipSeriesInterface)(nil).FindByDate), ctx, date)
}

// FindById mocks base method.
func (m *MockChampionshipSeriesInterface) FindById(ctx context.Context, id string) (*entity.ChampionshipSeries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*entity.ChampionshipSeries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockChampionshipSeriesInterfaceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockChampionshipSeriesInterface)(nil).FindById), ctx, id)
}
