// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/deck_asset.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/deck_asset.go -destination=./internal/mock/mock_repository/deck_asset.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeckAssetInterface is a mock of DeckAssetInterface interface.
type MockDeckAssetInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeckAssetInterfaceMockRecorder
	isgomock struct{}
}

// MockDeckAssetInterfaceMockRecorder is the mock recorder for MockDeckAssetInterface.
type MockDeckAssetInterfaceMockRecorder struct {
	mock *MockDeckAssetInterface
}

// NewMockDeckAssetInterface creates a new mock instance.
func NewMockDeckAssetInterface(ctrl *gomock.Controller) *MockDeckAssetInterface {
	mock := &MockDeckAssetInterface{ctrl: ctrl}
	mock.recorder = &MockDeckAssetInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeckAssetInterface) EXPECT() *MockDeckAssetInterfaceMockRecorder {
	return m.recorder
}

// UploadDeckImage mocks base method.
func (m *MockDeckAssetInterface) UploadDeckImage(ctx context.Context, deckCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadDeckImage", ctx, deckCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadDeckImage indicates an expected call of UploadDeckImage.
func (mr *MockDeckAssetInterfaceMockRecorder) UploadDeckImage(ctx, deckCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadDeckImage", reflect.TypeOf((*MockDeckAssetInterface)(nil).UploadDeckImage), ctx, deckCode)
}

// UploadDeckResultHTML mocks base method.
func (m *MockDeckAssetInterface) UploadDeckResultHTML(ctx context.Context, deckCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadDeckResultHTML", ctx, deckCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadDeckResultHTML indicates an expected call of UploadDeckResultHTML.
func (mr *MockDeckAssetInterfaceMockRecorder) UploadDeckResultHTML(ctx, deckCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadDeckResultHTML", reflect.TypeOf((*MockDeckAssetInterface)(nil).UploadDeckResultHTML), ctx, deckCode)
}
