// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/deck_code.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/deck_code.go -destination=./internal/mock/mock_repository/deck_code.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDeckCodeInterface is a mock of DeckCodeInterface interface.
type MockDeckCodeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeckCodeInterfaceMockRecorder
	isgomock struct{}
}

// MockDeckCodeInterfaceMockRecorder is the mock recorder for MockDeckCodeInterface.
type MockDeckCodeInterfaceMockRecorder struct {
	mock *MockDeckCodeInterface
}

// NewMockDeckCodeInterface creates a new mock instance.
func NewMockDeckCodeInterface(ctrl *gomock.Controller) *MockDeckCodeInterface {
	mock := &MockDeckCodeInterface{ctrl: ctrl}
	mock.recorder = &MockDeckCodeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeckCodeInterface) EXPECT() *MockDeckCodeInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeckCodeInterface) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeckCodeInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeckCodeInterface)(nil).Delete), ctx, id)
}

// FindByDeckId mocks base method.
func (m *MockDeckCodeInterface) FindByDeckId(ctx context.Context, deckId string) ([]*entity.DeckCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDeckId", ctx, deckId)
	ret0, _ := ret[0].([]*entity.DeckCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDeckId indicates an expected call of FindByDeckId.
func (mr *MockDeckCodeInterfaceMockRecorder) FindByDeckId(ctx, deckId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDeckId", reflect.TypeOf((*MockDeckCodeInterface)(nil).FindByDeckId), ctx, deckId)
}

// FindById mocks base method.
func (m *MockDeckCodeInterface) FindById(ctx context.Context, id string) (*entity.DeckCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*entity.DeckCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockDeckCodeInterfaceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockDeckCodeInterface)(nil).FindById), ctx, id)
}

// FindIdsByUserId mocks base method.
func (m *MockDeckCodeInterface) FindIdsByUserId(ctx context.Context, uid string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIdsByUserId", ctx, uid)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIdsByUserId indicates an expected call of FindIdsByUserId.
func (mr *MockDeckCodeInterfaceMockRecorder) FindIdsByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIdsByUserId", reflect.TypeOf((*MockDeckCodeInterface)(nil).FindIdsByUserId), ctx, uid)
}

// Save mocks base method.
func (m *MockDeckCodeInterface) Save(ctx context.Context, entity *entity.DeckCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockDeckCodeInterfaceMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDeckCodeInterface)(nil).Save), ctx, entity)
}
