// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/deck_usage_stat.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/deck_usage_stat.go -destination=./internal/mock/mock_repository/deck_usage_stat.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDeckUsageStatInterface is a mock of DeckUsageStatInterface interface.
type MockDeckUsageStatInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeckUsageStatInterfaceMockRecorder
	isgomock struct{}
}

// MockDeckUsageStatInterfaceMockRecorder is the mock recorder for MockDeckUsageStatInterface.
type MockDeckUsageStatInterfaceMockRecorder struct {
	mock *MockDeckUsageStatInterface
}

// NewMockDeckUsageStatInterface creates a new mock instance.
func NewMockDeckUsageStatInterface(ctrl *gomock.Controller) *MockDeckUsageStatInterface {
	mock := &MockDeckUsageStatInterface{ctrl: ctrl}
	mock.recorder = &MockDeckUsageStatInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeckUsageStatInterface) EXPECT() *MockDeckUsageStatInterfaceMockRecorder {
	return m.recorder
}

// FindDeckUsageStat mocks base method.
func (m *MockDeckUsageStatInterface) FindDeckUsageStat(ctx context.Context, userId string, fromDate, toDate time.Time) (*entity.DeckUsageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDeckUsageStat", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].(*entity.DeckUsageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDeckUsageStat indicates an expected call of FindDeckUsageStat.
func (mr *MockDeckUsageStatInterfaceMockRecorder) FindDeckUsageStat(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDeckUsageStat", reflect.TypeOf((*MockDeckUsageStatInterface)(nil).FindDeckUsageStat), ctx, userId, fromDate, toDate)
}
