// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/deck_code_post.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/deck_code_post.go -destination=./internal/mock/mock_repository/deck_code_post.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	repository "github.com/vsrecorder/core-apiserver/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockDeckCodePostInterface is a mock of DeckCodePostInterface interface.
type MockDeckCodePostInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeckCodePostInterfaceMockRecorder
	isgomock struct{}
}

// MockDeckCodePostInterfaceMockRecorder is the mock recorder for MockDeckCodePostInterface.
type MockDeckCodePostInterfaceMockRecorder struct {
	mock *MockDeckCodePostInterface
}

// NewMockDeckCodePostInterface creates a new mock instance.
func NewMockDeckCodePostInterface(ctrl *gomock.Controller) *MockDeckCodePostInterface {
	mock := &MockDeckCodePostInterface{ctrl: ctrl}
	mock.recorder = &MockDeckCodePostInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeckCodePostInterface) EXPECT() *MockDeckCodePostInterfaceMockRecorder {
	return m.recorder
}

// DeleteByUserId mocks base method.
func (m *MockDeckCodePostInterface) DeleteByUserId(ctx context.Context, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserId", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserId indicates an expected call of DeleteByUserId.
func (mr *MockDeckCodePostInterfaceMockRecorder) DeleteByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserId", reflect.TypeOf((*MockDeckCodePostInterface)(nil).DeleteByUserId), ctx, uid)
}

// Find mocks base method.
func (m *MockDeckCodePostInterface) Find(ctx context.Context, filter *repository.DeckCodePostFilter, limit, offset int) ([]*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockDeckCodePostInterfaceMockRecorder) Find(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockDeckCodePostInterface)(nil).Find), ctx, filter, limit, offset)
}

// FindActiveByDeckCodeId mocks base method.
func (m *MockDeckCodePostInterface) FindActiveByDeckCodeId(ctx context.Context, deckCodeId string) (*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByDeckCodeId", ctx, deckCodeId)
	ret0, _ := ret[0].(*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByDeckCodeId indicates an expected call of FindActiveByDeckCodeId.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindActiveByDeckCodeId(ctx, deckCodeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByDeckCodeId", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindActiveByDeckCodeId), ctx, deckCodeId)
}

// FindActiveByDeckId mocks base method.
func (m *MockDeckCodePostInterface) FindActiveByDeckId(ctx context.Context, deckId string) ([]*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByDeckId", ctx, deckId)
	ret0, _ := ret[0].([]*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByDeckId indicates an expected call of FindActiveByDeckId.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindActiveByDeckId(ctx, deckId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByDeckId", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindActiveByDeckId), ctx, deckId)
}

// FindById mocks base method.
func (m *MockDeckCodePostInterface) FindById(ctx context.Context, id, viewerUserId string) (*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id, viewerUserId)
	ret0, _ := ret[0].(*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindById(ctx, id, viewerUserId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindById), ctx, id, viewerUserId)
}

// FindByUserId mocks base method.
func (m *MockDeckCodePostInterface) FindByUserId(ctx context.Context, uid, viewerUserId string, limit, offset int) ([]*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, uid, viewerUserId, limit, offset)
	ret0, _ := ret[0].([]*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindByUserId(ctx, uid, viewerUserId, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindByUserId), ctx, uid, viewerUserId, limit, offset)
}

// FindLatestByDeckCodeId mocks base method.
func (m *MockDeckCodePostInterface) FindLatestByDeckCodeId(ctx context.Context, deckCodeId string) (*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestByDeckCodeId", ctx, deckCodeId)
	ret0, _ := ret[0].(*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestByDeckCodeId indicates an expected call of FindLatestByDeckCodeId.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindLatestByDeckCodeId(ctx, deckCodeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestByDeckCodeId", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindLatestByDeckCodeId), ctx, deckCodeId)
}

// FindLikeDigests mocks base method.
func (m *MockDeckCodePostInterface) FindLikeDigests(ctx context.Context, from, to time.Time) ([]*entity.DeckCodePostLikeDigest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLikeDigests", ctx, from, to)
	ret0, _ := ret[0].([]*entity.DeckCodePostLikeDigest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLikeDigests indicates an expected call of FindLikeDigests.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindLikeDigests(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLikeDigests", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindLikeDigests), ctx, from, to)
}

// FindLikers mocks base method.
func (m *MockDeckCodePostInterface) FindLikers(ctx context.Context, postId string, limit, offset int) ([]*entity.DeckCodePostLiker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLikers", ctx, postId, limit, offset)
	ret0, _ := ret[0].([]*entity.DeckCodePostLiker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLikers indicates an expected call of FindLikers.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindLikers(ctx, postId, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLikers", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindLikers), ctx, postId, limit, offset)
}

// FindLiteById mocks base method.
func (m *MockDeckCodePostInterface) FindLiteById(ctx context.Context, id string) (*entity.DeckCodePost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLiteById", ctx, id)
	ret0, _ := ret[0].(*entity.DeckCodePost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLiteById indicates an expected call of FindLiteById.
func (mr *MockDeckCodePostInterfaceMockRecorder) FindLiteById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLiteById", reflect.TypeOf((*MockDeckCodePostInterface)(nil).FindLiteById), ctx, id)
}

// Like mocks base method.
func (m *MockDeckCodePostInterface) Like(ctx context.Context, postId, uid string, createdAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, postId, uid, createdAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockDeckCodePostInterfaceMockRecorder) Like(ctx, postId, uid, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockDeckCodePostInterface)(nil).Like), ctx, postId, uid, createdAt)
}

// RecordImport mocks base method.
func (m *MockDeckCodePostInterface) RecordImport(ctx context.Context, postId, uid string, createdAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordImport", ctx, postId, uid, createdAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordImport indicates an expected call of RecordImport.
func (mr *MockDeckCodePostInterfaceMockRecorder) RecordImport(ctx, postId, uid, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordImport", reflect.TypeOf((*MockDeckCodePostInterface)(nil).RecordImport), ctx, postId, uid, createdAt)
}

// Save mocks base method.
func (m *MockDeckCodePostInterface) Save(ctx context.Context, entity *entity.DeckCodePost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockDeckCodePostInterfaceMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDeckCodePostInterface)(nil).Save), ctx, entity)
}

// SummarizeByUserId mocks base method.
func (m *MockDeckCodePostInterface) SummarizeByUserId(ctx context.Context, uid string) (*entity.DeckCodePostUserSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummarizeByUserId", ctx, uid)
	ret0, _ := ret[0].(*entity.DeckCodePostUserSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SummarizeByUserId indicates an expected call of SummarizeByUserId.
func (mr *MockDeckCodePostInterfaceMockRecorder) SummarizeByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummarizeByUserId", reflect.TypeOf((*MockDeckCodePostInterface)(nil).SummarizeByUserId), ctx, uid)
}

// Unlike mocks base method.
func (m *MockDeckCodePostInterface) Unlike(ctx context.Context, postId, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlike", ctx, postId, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlike indicates an expected call of Unlike.
func (mr *MockDeckCodePostInterfaceMockRecorder) Unlike(ctx, postId, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlike", reflect.TypeOf((*MockDeckCodePostInterface)(nil).Unlike), ctx, postId, uid)
}

// Unpublish mocks base method.
func (m *MockDeckCodePostInterface) Unpublish(ctx context.Context, id string, unpublishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpublish", ctx, id, unpublishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unpublish indicates an expected call of Unpublish.
func (mr *MockDeckCodePostInterfaceMockRecorder) Unpublish(ctx, id, unpublishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpublish", reflect.TypeOf((*MockDeckCodePostInterface)(nil).Unpublish), ctx, id, unpublishedAt)
}

// UnpublishByDeckCodeId mocks base method.
func (m *MockDeckCodePostInterface) UnpublishByDeckCodeId(ctx context.Context, deckCodeId string, unpublishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpublishByDeckCodeId", ctx, deckCodeId, unpublishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpublishByDeckCodeId indicates an expected call of UnpublishByDeckCodeId.
func (mr *MockDeckCodePostInterfaceMockRecorder) UnpublishByDeckCodeId(ctx, deckCodeId, unpublishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpublishByDeckCodeId", reflect.TypeOf((*MockDeckCodePostInterface)(nil).UnpublishByDeckCodeId), ctx, deckCodeId, unpublishedAt)
}

// UnpublishByDeckId mocks base method.
func (m *MockDeckCodePostInterface) UnpublishByDeckId(ctx context.Context, deckId string, unpublishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpublishByDeckId", ctx, deckId, unpublishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpublishByDeckId indicates an expected call of UnpublishByDeckId.
func (mr *MockDeckCodePostInterfaceMockRecorder) UnpublishByDeckId(ctx, deckId, unpublishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpublishByDeckId", reflect.TypeOf((*MockDeckCodePostInterface)(nil).UnpublishByDeckId), ctx, deckId, unpublishedAt)
}

// MockDeckCardInterface is a mock of DeckCardInterface interface.
type MockDeckCardInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeckCardInterfaceMockRecorder
	isgomock struct{}
}

// MockDeckCardInterfaceMockRecorder is the mock recorder for MockDeckCardInterface.
type MockDeckCardInterfaceMockRecorder struct {
	mock *MockDeckCardInterface
}

// NewMockDeckCardInterface creates a new mock instance.
func NewMockDeckCardInterface(ctrl *gomock.Controller) *MockDeckCardInterface {
	mock := &MockDeckCardInterface{ctrl: ctrl}
	mock.recorder = &MockDeckCardInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeckCardInterface) EXPECT() *MockDeckCardInterfaceMockRecorder {
	return m.recorder
}

// FindAceSpec mocks base method.
func (m *MockDeckCardInterface) FindAceSpec(ctx context.Context, deckCode string) (*entity.AceSpecCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAceSpec", ctx, deckCode)
	ret0, _ := ret[0].(*entity.AceSpecCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAceSpec indicates an expected call of FindAceSpec.
func (mr *MockDeckCardInterfaceMockRecorder) FindAceSpec(ctx, deckCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAceSpec", reflect.TypeOf((*MockDeckCardInterface)(nil).FindAceSpec), ctx, deckCode)
}
