// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/designation_stats.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/designation_stats.go -destination=./internal/mock/mock_repository/designation_stats.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDesignationStatsInterface is a mock of DesignationStatsInterface interface.
type MockDesignationStatsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDesignationStatsInterfaceMockRecorder
	isgomock struct{}
}

// MockDesignationStatsInterfaceMockRecorder is the mock recorder for MockDesignationStatsInterface.
type MockDesignationStatsInterfaceMockRecorder struct {
	mock *MockDesignationStatsInterface
}

// NewMockDesignationStatsInterface creates a new mock instance.
func NewMockDesignationStatsInterface(ctrl *gomock.Controller) *MockDesignationStatsInterface {
	mock := &MockDesignationStatsInterface{ctrl: ctrl}
	mock.recorder = &MockDesignationStatsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDesignationStatsInterface) EXPECT() *MockDesignationStatsInterfaceMockRecorder {
	return m.recorder
}

// CountCityLeagueRecordsByUserId mocks base method.
func (m *MockDesignationStatsInterface) CountCityLeagueRecordsByUserId(ctx context.Context, userId string, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCityLeagueRecordsByUserId", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCityLeagueRecordsByUserId indicates an expected call of CountCityLeagueRecordsByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) CountCityLeagueRecordsByUserId(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCityLeagueRecordsByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).CountCityLeagueRecordsByUserId), ctx, userId, fromDate, toDate)
}

// CountCityLeagueRecordsGroupByUserId mocks base method.
func (m *MockDesignationStatsInterface) CountCityLeagueRecordsGroupByUserId(ctx context.Context, fromDate, toDate time.Time) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCityLeagueRecordsGroupByUserId", ctx, fromDate, toDate)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCityLeagueRecordsGroupByUserId indicates an expected call of CountCityLeagueRecordsGroupByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) CountCityLeagueRecordsGroupByUserId(ctx, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCityLeagueRecordsGroupByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).CountCityLeagueRecordsGroupByUserId), ctx, fromDate, toDate)
}

// CountLeagueRecordsByUserId mocks base method.
func (m *MockDesignationStatsInterface) CountLeagueRecordsByUserId(ctx context.Context, userId string, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLeagueRecordsByUserId", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLeagueRecordsByUserId indicates an expected call of CountLeagueRecordsByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) CountLeagueRecordsByUserId(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLeagueRecordsByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).CountLeagueRecordsByUserId), ctx, userId, fromDate, toDate)
}

// CountLeagueRecordsGroupByUserId mocks base method.
func (m *MockDesignationStatsInterface) CountLeagueRecordsGroupByUserId(ctx context.Context, fromDate, toDate time.Time) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLeagueRecordsGroupByUserId", ctx, fromDate, toDate)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLeagueRecordsGroupByUserId indicates an expected call of CountLeagueRecordsGroupByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) CountLeagueRecordsGroupByUserId(ctx, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLeagueRecordsGroupByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).CountLeagueRecordsGroupByUserId), ctx, fromDate, toDate)
}

// CountRecordsAsOfByUserId mocks base method.
func (m *MockDesignationStatsInterface) CountRecordsAsOfByUserId(ctx context.Context, userId string, fromDate, asOf time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecordsAsOfByUserId", ctx, userId, fromDate, asOf)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecordsAsOfByUserId indicates an expected call of CountRecordsAsOfByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) CountRecordsAsOfByUserId(ctx, userId, fromDate, asOf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecordsAsOfByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).CountRecordsAsOfByUserId), ctx, userId, fromDate, asOf)
}

// CountRecordsByUserId mocks base method.
func (m *MockDesignationStatsInterface) CountRecordsByUserId(ctx context.Context, userId string, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecordsByUserId", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecordsByUserId indicates an expected call of CountRecordsByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) CountRecordsByUserId(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecordsByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).CountRecordsByUserId), ctx, userId, fromDate, toDate)
}

// CountRecordsGroupByUserId mocks base method.
func (m *MockDesignationStatsInterface) CountRecordsGroupByUserId(ctx context.Context, fromDate, toDate time.Time) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecordsGroupByUserId", ctx, fromDate, toDate)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecordsGroupByUserId indicates an expected call of CountRecordsGroupByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) CountRecordsGroupByUserId(ctx, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecordsGroupByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).CountRecordsGroupByUserId), ctx, fromDate, toDate)
}

// ExistsCityLeagueFinalTournamentResultAsOfByPlayerId mocks base method.
func (m *MockDesignationStatsInterface) ExistsCityLeagueFinalTournamentResultAsOfByPlayerId(ctx context.Context, userId, playerId string, maxRank int, fromDate, asOf time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCityLeagueFinalTournamentResultAsOfByPlayerId", ctx, userId, playerId, maxRank, fromDate, asOf)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCityLeagueFinalTournamentResultAsOfByPlayerId indicates an expected call of ExistsCityLeagueFinalTournamentResultAsOfByPlayerId.
func (mr *MockDesignationStatsInterfaceMockRecorder) ExistsCityLeagueFinalTournamentResultAsOfByPlayerId(ctx, userId, playerId, maxRank, fromDate, asOf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCityLeagueFinalTournamentResultAsOfByPlayerId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).ExistsCityLeagueFinalTournamentResultAsOfByPlayerId), ctx, userId, playerId, maxRank, fromDate, asOf)
}

// ExistsCityLeagueFinalTournamentResultByPlayerId mocks base method.
func (m *MockDesignationStatsInterface) ExistsCityLeagueFinalTournamentResultByPlayerId(ctx context.Context, userId, playerId string, maxRank int, fromDate, toDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCityLeagueFinalTournamentResultByPlayerId", ctx, userId, playerId, maxRank, fromDate, toDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCityLeagueFinalTournamentResultByPlayerId indicates an expected call of ExistsCityLeagueFinalTournamentResultByPlayerId.
func (mr *MockDesignationStatsInterfaceMockRecorder) ExistsCityLeagueFinalTournamentResultByPlayerId(ctx, userId, playerId, maxRank, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCityLeagueFinalTournamentResultByPlayerId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).ExistsCityLeagueFinalTournamentResultByPlayerId), ctx, userId, playerId, maxRank, fromDate, toDate)
}

// ExistsCityLeagueFinalTournamentResultGroupByUserId mocks base method.
func (m *MockDesignationStatsInterface) ExistsCityLeagueFinalTournamentResultGroupByUserId(ctx context.Context, maxRank int, fromDate, toDate time.Time) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCityLeagueFinalTournamentResultGroupByUserId", ctx, maxRank, fromDate, toDate)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCityLeagueFinalTournamentResultGroupByUserId indicates an expected call of ExistsCityLeagueFinalTournamentResultGroupByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) ExistsCityLeagueFinalTournamentResultGroupByUserId(ctx, maxRank, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCityLeagueFinalTournamentResultGroupByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).ExistsCityLeagueFinalTournamentResultGroupByUserId), ctx, maxRank, fromDate, toDate)
}

// ExistsCityLeagueFinalTournamentResultWithoutMatchingRecordByPlayerId mocks base method.
func (m *MockDesignationStatsInterface) ExistsCityLeagueFinalTournamentResultWithoutMatchingRecordByPlayerId(ctx context.Context, userId, playerId string, maxRank int, fromDate, toDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCityLeagueFinalTournamentResultWithoutMatchingRecordByPlayerId", ctx, userId, playerId, maxRank, fromDate, toDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCityLeagueFinalTournamentResultWithoutMatchingRecordByPlayerId indicates an expected call of ExistsCityLeagueFinalTournamentResultWithoutMatchingRecordByPlayerId.
func (mr *MockDesignationStatsInterfaceMockRecorder) ExistsCityLeagueFinalTournamentResultWithoutMatchingRecordByPlayerId(ctx, userId, playerId, maxRank, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCityLeagueFinalTournamentResultWithoutMatchingRecordByPlayerId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).ExistsCityLeagueFinalTournamentResultWithoutMatchingRecordByPlayerId), ctx, userId, playerId, maxRank, fromDate, toDate)
}

// ExistsCityLeagueResultAsOfByPlayerId mocks base method.
func (m *MockDesignationStatsInterface) ExistsCityLeagueResultAsOfByPlayerId(ctx context.Context, userId, playerId string, fromDate, asOf time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCityLeagueResultAsOfByPlayerId", ctx, userId, playerId, fromDate, asOf)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCityLeagueResultAsOfByPlayerId indicates an expected call of ExistsCityLeagueResultAsOfByPlayerId.
func (mr *MockDesignationStatsInterfaceMockRecorder) ExistsCityLeagueResultAsOfByPlayerId(ctx, userId, playerId, fromDate, asOf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCityLeagueResultAsOfByPlayerId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).ExistsCityLeagueResultAsOfByPlayerId), ctx, userId, playerId, fromDate, asOf)
}

// ExistsCityLeagueResultByPlayerId mocks base method.
func (m *MockDesignationStatsInterface) ExistsCityLeagueResultByPlayerId(ctx context.Context, userId, playerId string, fromDate, toDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCityLeagueResultByPlayerId", ctx, userId, playerId, fromDate, toDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCityLeagueResultByPlayerId indicates an expected call of ExistsCityLeagueResultByPlayerId.
func (mr *MockDesignationStatsInterfaceMockRecorder) ExistsCityLeagueResultByPlayerId(ctx, userId, playerId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCityLeagueResultByPlayerId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).ExistsCityLeagueResultByPlayerId), ctx, userId, playerId, fromDate, toDate)
}

// ExistsCityLeagueResultGroupByUserId mocks base method.
func (m *MockDesignationStatsInterface) ExistsCityLeagueResultGroupByUserId(ctx context.Context, fromDate, toDate time.Time) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCityLeagueResultGroupByUserId", ctx, fromDate, toDate)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCityLeagueResultGroupByUserId indicates an expected call of ExistsCityLeagueResultGroupByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) ExistsCityLeagueResultGroupByUserId(ctx, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCityLeagueResultGroupByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).ExistsCityLeagueResultGroupByUserId), ctx, fromDate, toDate)
}

// ExistsCityLeagueResultWithoutMatchingRecordByPlayerId mocks base method.
func (m *MockDesignationStatsInterface) ExistsCityLeagueResultWithoutMatchingRecordByPlayerId(ctx context.Context, userId, playerId string, fromDate, toDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCityLeagueResultWithoutMatchingRecordByPlayerId", ctx, userId, playerId, fromDate, toDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCityLeagueResultWithoutMatchingRecordByPlayerId indicates an expected call of ExistsCityLeagueResultWithoutMatchingRecordByPlayerId.
func (mr *MockDesignationStatsInterfaceMockRecorder) ExistsCityLeagueResultWithoutMatchingRecordByPlayerId(ctx, userId, playerId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCityLeagueResultWithoutMatchingRecordByPlayerId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).ExistsCityLeagueResultWithoutMatchingRecordByPlayerId), ctx, userId, playerId, fromDate, toDate)
}
