// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/designation.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/designation.go -destination=./internal/mock/mock_repository/designation.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDesignationInterface is a mock of DesignationInterface interface.
type MockDesignationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDesignationInterfaceMockRecorder
	isgomock struct{}
}

// MockDesignationInterfaceMockRecorder is the mock recorder for MockDesignationInterface.
type MockDesignationInterfaceMockRecorder struct {
	mock *MockDesignationInterface
}

// NewMockDesignationInterface creates a new mock instance.
func NewMockDesignationInterface(ctrl *gomock.Controller) *MockDesignationInterface {
	mock := &MockDesignationInterface{ctrl: ctrl}
	mock.recorder = &MockDesignationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDesignationInterface) EXPECT() *MockDesignationInterfaceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockDesignationInterface) FindAll(ctx context.Context) ([]*entity.Designation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*entity.Designation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockDesignationInterfaceMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockDesignationInterface)(nil).FindAll), ctx)
}
