// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/designation_stats.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/designation_stats.go -destination=./internal/mock/mock_repository/designation_stats.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDesignationStatsInterface is a mock of DesignationStatsInterface interface.
type MockDesignationStatsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDesignationStatsInterfaceMockRecorder
	isgomock struct{}
}

// MockDesignationStatsInterfaceMockRecorder is the mock recorder for MockDesignationStatsInterface.
type MockDesignationStatsInterfaceMockRecorder struct {
	mock *MockDesignationStatsInterface
}

// NewMockDesignationStatsInterface creates a new mock instance.
func NewMockDesignationStatsInterface(ctrl *gomock.Controller) *MockDesignationStatsInterface {
	mock := &MockDesignationStatsInterface{ctrl: ctrl}
	mock.recorder = &MockDesignationStatsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDesignationStatsInterface) EXPECT() *MockDesignationStatsInterfaceMockRecorder {
	return m.recorder
}

// CountCityLeagueRecordsByUserId mocks base method.
func (m *MockDesignationStatsInterface) CountCityLeagueRecordsByUserId(ctx context.Context, userId string, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCityLeagueRecordsByUserId", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCityLeagueRecordsByUserId indicates an expected call of CountCityLeagueRecordsByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) CountCityLeagueRecordsByUserId(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCityLeagueRecordsByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).CountCityLeagueRecordsByUserId), ctx, userId, fromDate, toDate)
}

// CountGymBattleRecordsByUserId mocks base method.
func (m *MockDesignationStatsInterface) CountGymBattleRecordsByUserId(ctx context.Context, userId string, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountGymBattleRecordsByUserId", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountGymBattleRecordsByUserId indicates an expected call of CountGymBattleRecordsByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) CountGymBattleRecordsByUserId(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountGymBattleRecordsByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).CountGymBattleRecordsByUserId), ctx, userId, fromDate, toDate)
}

// CountLeagueRecordsByUserId mocks base method.
func (m *MockDesignationStatsInterface) CountLeagueRecordsByUserId(ctx context.Context, userId string, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLeagueRecordsByUserId", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLeagueRecordsByUserId indicates an expected call of CountLeagueRecordsByUserId.
func (mr *MockDesignationStatsInterfaceMockRecorder) CountLeagueRecordsByUserId(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLeagueRecordsByUserId", reflect.TypeOf((*MockDesignationStatsInterface)(nil).CountLeagueRecordsByUserId), ctx, userId, fromDate, toDate)
}
