// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/kizuna.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/kizuna.go -destination=./internal/mock/mock_repository/kizuna.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockKizunaInterface is a mock of KizunaInterface interface.
type MockKizunaInterface struct {
	ctrl     *gomock.Controller
	recorder *MockKizunaInterfaceMockRecorder
	isgomock struct{}
}

// MockKizunaInterfaceMockRecorder is the mock recorder for MockKizunaInterface.
type MockKizunaInterfaceMockRecorder struct {
	mock *MockKizunaInterface
}

// NewMockKizunaInterface creates a new mock instance.
func NewMockKizunaInterface(ctrl *gomock.Controller) *MockKizunaInterface {
	mock := &MockKizunaInterface{ctrl: ctrl}
	mock.recorder = &MockKizunaInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKizunaInterface) EXPECT() *MockKizunaInterfaceMockRecorder {
	return m.recorder
}

// FindKizunaDeckAggregates mocks base method.
func (m *MockKizunaInterface) FindKizunaDeckAggregates(ctx context.Context, userId string) ([]*entity.KizunaDeckAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindKizunaDeckAggregates", ctx, userId)
	ret0, _ := ret[0].([]*entity.KizunaDeckAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindKizunaDeckAggregates indicates an expected call of FindKizunaDeckAggregates.
func (mr *MockKizunaInterfaceMockRecorder) FindKizunaDeckAggregates(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindKizunaDeckAggregates", reflect.TypeOf((*MockKizunaInterface)(nil).FindKizunaDeckAggregates), ctx, userId)
}
