// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/notification.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/notification.go -destination=./internal/mock/mock_repository/notification.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationInterface is a mock of NotificationInterface interface.
type MockNotificationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationInterfaceMockRecorder
	isgomock struct{}
}

// MockNotificationInterfaceMockRecorder is the mock recorder for MockNotificationInterface.
type MockNotificationInterfaceMockRecorder struct {
	mock *MockNotificationInterface
}

// NewMockNotificationInterface creates a new mock instance.
func NewMockNotificationInterface(ctrl *gomock.Controller) *MockNotificationInterface {
	mock := &MockNotificationInterface{ctrl: ctrl}
	mock.recorder = &MockNotificationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationInterface) EXPECT() *MockNotificationInterfaceMockRecorder {
	return m.recorder
}

// CountUnreadByUserId mocks base method.
func (m *MockNotificationInterface) CountUnreadByUserId(ctx context.Context, userId string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnreadByUserId", ctx, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnreadByUserId indicates an expected call of CountUnreadByUserId.
func (mr *MockNotificationInterfaceMockRecorder) CountUnreadByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnreadByUserId", reflect.TypeOf((*MockNotificationInterface)(nil).CountUnreadByUserId), ctx, userId)
}

// FindByUserId mocks base method.
func (m *MockNotificationInterface) FindByUserId(ctx context.Context, userId string, limit int) ([]*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, userId, limit)
	ret0, _ := ret[0].([]*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockNotificationInterfaceMockRecorder) FindByUserId(ctx, userId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockNotificationInterface)(nil).FindByUserId), ctx, userId, limit)
}

// MarkAllAsReadByUserId mocks base method.
func (m *MockNotificationInterface) MarkAllAsReadByUserId(ctx context.Context, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllAsReadByUserId", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllAsReadByUserId indicates an expected call of MarkAllAsReadByUserId.
func (mr *MockNotificationInterfaceMockRecorder) MarkAllAsReadByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllAsReadByUserId", reflect.TypeOf((*MockNotificationInterface)(nil).MarkAllAsReadByUserId), ctx, userId)
}

// MarkAsRead mocks base method.
func (m *MockNotificationInterface) MarkAsRead(ctx context.Context, id, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, id, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockNotificationInterfaceMockRecorder) MarkAsRead(ctx, id, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockNotificationInterface)(nil).MarkAsRead), ctx, id, userId)
}

// Save mocks base method.
func (m *MockNotificationInterface) Save(ctx context.Context, entity *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockNotificationInterfaceMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockNotificationInterface)(nil).Save), ctx, entity)
}
