// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/official_event_environment.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/official_event_environment.go -destination=./internal/mock/mock_repository/official_event_environment.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOfficialEventEnvironmentInterface is a mock of OfficialEventEnvironmentInterface interface.
type MockOfficialEventEnvironmentInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOfficialEventEnvironmentInterfaceMockRecorder
	isgomock struct{}
}

// MockOfficialEventEnvironmentInterfaceMockRecorder is the mock recorder for MockOfficialEventEnvironmentInterface.
type MockOfficialEventEnvironmentInterfaceMockRecorder struct {
	mock *MockOfficialEventEnvironmentInterface
}

// NewMockOfficialEventEnvironmentInterface creates a new mock instance.
func NewMockOfficialEventEnvironmentInterface(ctrl *gomock.Controller) *MockOfficialEventEnvironmentInterface {
	mock := &MockOfficialEventEnvironmentInterface{ctrl: ctrl}
	mock.recorder = &MockOfficialEventEnvironmentInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfficialEventEnvironmentInterface) EXPECT() *MockOfficialEventEnvironmentInterfaceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockOfficialEventEnvironmentInterface) FindAll(ctx context.Context) (map[uint]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].(map[uint]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockOfficialEventEnvironmentInterfaceMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockOfficialEventEnvironmentInterface)(nil).FindAll), ctx)
}

// FindEnvironmentIdByOfficialEventId mocks base method.
func (m *MockOfficialEventEnvironmentInterface) FindEnvironmentIdByOfficialEventId(ctx context.Context, officialEventId uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEnvironmentIdByOfficialEventId", ctx, officialEventId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindEnvironmentIdByOfficialEventId indicates an expected call of FindEnvironmentIdByOfficialEventId.
func (mr *MockOfficialEventEnvironmentInterfaceMockRecorder) FindEnvironmentIdByOfficialEventId(ctx, officialEventId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEnvironmentIdByOfficialEventId", reflect.TypeOf((*MockOfficialEventEnvironmentInterface)(nil).FindEnvironmentIdByOfficialEventId), ctx, officialEventId)
}
