// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/opponent_deck.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/opponent_deck.go -destination=./internal/mock/mock_repository/opponent_deck.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOpponentDeckInterface is a mock of OpponentDeckInterface interface.
type MockOpponentDeckInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOpponentDeckInterfaceMockRecorder
	isgomock struct{}
}

// MockOpponentDeckInterfaceMockRecorder is the mock recorder for MockOpponentDeckInterface.
type MockOpponentDeckInterfaceMockRecorder struct {
	mock *MockOpponentDeckInterface
}

// NewMockOpponentDeckInterface creates a new mock instance.
func NewMockOpponentDeckInterface(ctrl *gomock.Controller) *MockOpponentDeckInterface {
	mock := &MockOpponentDeckInterface{ctrl: ctrl}
	mock.recorder = &MockOpponentDeckInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpponentDeckInterface) EXPECT() *MockOpponentDeckInterfaceMockRecorder {
	return m.recorder
}

// FindByUserId mocks base method.
func (m *MockOpponentDeckInterface) FindByUserId(ctx context.Context, userId string) ([]*entity.OpponentDeck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, userId)
	ret0, _ := ret[0].([]*entity.OpponentDeck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockOpponentDeckInterfaceMockRecorder) FindByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockOpponentDeckInterface)(nil).FindByUserId), ctx, userId)
}

// FindMatchesBySpec mocks base method.
func (m *MockOpponentDeckInterface) FindMatchesBySpec(ctx context.Context, userId string, spec *entity.OpponentDeckSpec) ([]*entity.OpponentDeckMatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMatchesBySpec", ctx, userId, spec)
	ret0, _ := ret[0].([]*entity.OpponentDeckMatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMatchesBySpec indicates an expected call of FindMatchesBySpec.
func (mr *MockOpponentDeckInterfaceMockRecorder) FindMatchesBySpec(ctx, userId, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMatchesBySpec", reflect.TypeOf((*MockOpponentDeckInterface)(nil).FindMatchesBySpec), ctx, userId, spec)
}

// Replace mocks base method.
func (m *MockOpponentDeckInterface) Replace(ctx context.Context, userId string, from, to *entity.OpponentDeckSpec) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, userId, from, to)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockOpponentDeckInterfaceMockRecorder) Replace(ctx, userId, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockOpponentDeckInterface)(nil).Replace), ctx, userId, from, to)
}
