// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/opponent_deck_usage_stat.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/opponent_deck_usage_stat.go -destination=./internal/mock/mock_repository/opponent_deck_usage_stat.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOpponentDeckUsageStatInterface is a mock of OpponentDeckUsageStatInterface interface.
type MockOpponentDeckUsageStatInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOpponentDeckUsageStatInterfaceMockRecorder
	isgomock struct{}
}

// MockOpponentDeckUsageStatInterfaceMockRecorder is the mock recorder for MockOpponentDeckUsageStatInterface.
type MockOpponentDeckUsageStatInterfaceMockRecorder struct {
	mock *MockOpponentDeckUsageStatInterface
}

// NewMockOpponentDeckUsageStatInterface creates a new mock instance.
func NewMockOpponentDeckUsageStatInterface(ctrl *gomock.Controller) *MockOpponentDeckUsageStatInterface {
	mock := &MockOpponentDeckUsageStatInterface{ctrl: ctrl}
	mock.recorder = &MockOpponentDeckUsageStatInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpponentDeckUsageStatInterface) EXPECT() *MockOpponentDeckUsageStatInterfaceMockRecorder {
	return m.recorder
}

// FindOpponentDeckUsageStat mocks base method.
func (m *MockOpponentDeckUsageStatInterface) FindOpponentDeckUsageStat(ctx context.Context, userId string, fromDate, toDate time.Time, deckId string) (*entity.OpponentDeckUsageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOpponentDeckUsageStat", ctx, userId, fromDate, toDate, deckId)
	ret0, _ := ret[0].(*entity.OpponentDeckUsageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOpponentDeckUsageStat indicates an expected call of FindOpponentDeckUsageStat.
func (mr *MockOpponentDeckUsageStatInterfaceMockRecorder) FindOpponentDeckUsageStat(ctx, userId, fromDate, toDate, deckId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOpponentDeckUsageStat", reflect.TypeOf((*MockOpponentDeckUsageStatInterface)(nil).FindOpponentDeckUsageStat), ctx, userId, fromDate, toDate, deckId)
}
