// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/player_ranking.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/player_ranking.go -destination=./internal/mock/mock_repository/player_ranking.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayerRankingInterface is a mock of PlayerRankingInterface interface.
type MockPlayerRankingInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerRankingInterfaceMockRecorder
	isgomock struct{}
}

// MockPlayerRankingInterfaceMockRecorder is the mock recorder for MockPlayerRankingInterface.
type MockPlayerRankingInterfaceMockRecorder struct {
	mock *MockPlayerRankingInterface
}

// NewMockPlayerRankingInterface creates a new mock instance.
func NewMockPlayerRankingInterface(ctrl *gomock.Controller) *MockPlayerRankingInterface {
	mock := &MockPlayerRankingInterface{ctrl: ctrl}
	mock.recorder = &MockPlayerRankingInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerRankingInterface) EXPECT() *MockPlayerRankingInterfaceMockRecorder {
	return m.recorder
}

// FindLatestByPlayerId mocks base method.
func (m *MockPlayerRankingInterface) FindLatestByPlayerId(ctx context.Context, playerId string) (*entity.PlayerRanking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestByPlayerId", ctx, playerId)
	ret0, _ := ret[0].(*entity.PlayerRanking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestByPlayerId indicates an expected call of FindLatestByPlayerId.
func (mr *MockPlayerRankingInterfaceMockRecorder) FindLatestByPlayerId(ctx, playerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestByPlayerId", reflect.TypeOf((*MockPlayerRankingInterface)(nil).FindLatestByPlayerId), ctx, playerId)
}
