// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/pokemon_sprite.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/pokemon_sprite.go -destination=./internal/mock/mock_repository/pokemon_sprite.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPokemonSpriteNameInterface is a mock of PokemonSpriteNameInterface interface.
type MockPokemonSpriteNameInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPokemonSpriteNameInterfaceMockRecorder
	isgomock struct{}
}

// MockPokemonSpriteNameInterfaceMockRecorder is the mock recorder for MockPokemonSpriteNameInterface.
type MockPokemonSpriteNameInterfaceMockRecorder struct {
	mock *MockPokemonSpriteNameInterface
}

// NewMockPokemonSpriteNameInterface creates a new mock instance.
func NewMockPokemonSpriteNameInterface(ctrl *gomock.Controller) *MockPokemonSpriteNameInterface {
	mock := &MockPokemonSpriteNameInterface{ctrl: ctrl}
	mock.recorder = &MockPokemonSpriteNameInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPokemonSpriteNameInterface) EXPECT() *MockPokemonSpriteNameInterfaceMockRecorder {
	return m.recorder
}

// FindNamesByIds mocks base method.
func (m *MockPokemonSpriteNameInterface) FindNamesByIds(ctx context.Context, ids []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNamesByIds", ctx, ids)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNamesByIds indicates an expected call of FindNamesByIds.
func (mr *MockPokemonSpriteNameInterfaceMockRecorder) FindNamesByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNamesByIds", reflect.TypeOf((*MockPokemonSpriteNameInterface)(nil).FindNamesByIds), ctx, ids)
}
