// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/pokemon_avatar.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/pokemon_avatar.go -destination=./internal/mock/mock_repository/pokemon_avatar.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPokemonAvatarInterface is a mock of PokemonAvatarInterface interface.
type MockPokemonAvatarInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPokemonAvatarInterfaceMockRecorder
	isgomock struct{}
}

// MockPokemonAvatarInterfaceMockRecorder is the mock recorder for MockPokemonAvatarInterface.
type MockPokemonAvatarInterfaceMockRecorder struct {
	mock *MockPokemonAvatarInterface
}

// NewMockPokemonAvatarInterface creates a new mock instance.
func NewMockPokemonAvatarInterface(ctrl *gomock.Controller) *MockPokemonAvatarInterface {
	mock := &MockPokemonAvatarInterface{ctrl: ctrl}
	mock.recorder = &MockPokemonAvatarInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPokemonAvatarInterface) EXPECT() *MockPokemonAvatarInterfaceMockRecorder {
	return m.recorder
}

// FindRandomExcludingImageURL mocks base method.
func (m *MockPokemonAvatarInterface) FindRandomExcludingImageURL(ctx context.Context, imageURL string) (*entity.PokemonAvatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRandomExcludingImageURL", ctx, imageURL)
	ret0, _ := ret[0].(*entity.PokemonAvatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRandomExcludingImageURL indicates an expected call of FindRandomExcludingImageURL.
func (mr *MockPokemonAvatarInterfaceMockRecorder) FindRandomExcludingImageURL(ctx, imageURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRandomExcludingImageURL", reflect.TypeOf((*MockPokemonAvatarInterface)(nil).FindRandomExcludingImageURL), ctx, imageURL)
}
