// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/push_sender.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/push_sender.go -destination=./internal/mock/mock_repository/push_sender.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPushSenderInterface is a mock of PushSenderInterface interface.
type MockPushSenderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPushSenderInterfaceMockRecorder
	isgomock struct{}
}

// MockPushSenderInterfaceMockRecorder is the mock recorder for MockPushSenderInterface.
type MockPushSenderInterfaceMockRecorder struct {
	mock *MockPushSenderInterface
}

// NewMockPushSenderInterface creates a new mock instance.
func NewMockPushSenderInterface(ctrl *gomock.Controller) *MockPushSenderInterface {
	mock := &MockPushSenderInterface{ctrl: ctrl}
	mock.recorder = &MockPushSenderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushSenderInterface) EXPECT() *MockPushSenderInterfaceMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *MockPushSenderInterface) Enabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockPushSenderInterfaceMockRecorder) Enabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockPushSenderInterface)(nil).Enabled))
}

// Send mocks base method.
func (m *MockPushSenderInterface) Send(ctx context.Context, subscription *entity.PushSubscription, payload *entity.PushPayload) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, subscription, payload)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockPushSenderInterfaceMockRecorder) Send(ctx, subscription, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockPushSenderInterface)(nil).Send), ctx, subscription, payload)
}
