// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/push_subscription.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/push_subscription.go -destination=./internal/mock/mock_repository/push_subscription.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPushSubscriptionInterface is a mock of PushSubscriptionInterface interface.
type MockPushSubscriptionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPushSubscriptionInterfaceMockRecorder
	isgomock struct{}
}

// MockPushSubscriptionInterfaceMockRecorder is the mock recorder for MockPushSubscriptionInterface.
type MockPushSubscriptionInterfaceMockRecorder struct {
	mock *MockPushSubscriptionInterface
}

// NewMockPushSubscriptionInterface creates a new mock instance.
func NewMockPushSubscriptionInterface(ctrl *gomock.Controller) *MockPushSubscriptionInterface {
	mock := &MockPushSubscriptionInterface{ctrl: ctrl}
	mock.recorder = &MockPushSubscriptionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushSubscriptionInterface) EXPECT() *MockPushSubscriptionInterfaceMockRecorder {
	return m.recorder
}

// DeleteByUserId mocks base method.
func (m *MockPushSubscriptionInterface) DeleteByUserId(ctx context.Context, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserId", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserId indicates an expected call of DeleteByUserId.
func (mr *MockPushSubscriptionInterfaceMockRecorder) DeleteByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserId", reflect.TypeOf((*MockPushSubscriptionInterface)(nil).DeleteByUserId), ctx, uid)
}

// FindLiveByUserId mocks base method.
func (m *MockPushSubscriptionInterface) FindLiveByUserId(ctx context.Context, userId string) ([]*entity.PushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLiveByUserId", ctx, userId)
	ret0, _ := ret[0].([]*entity.PushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLiveByUserId indicates an expected call of FindLiveByUserId.
func (mr *MockPushSubscriptionInterfaceMockRecorder) FindLiveByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLiveByUserId", reflect.TypeOf((*MockPushSubscriptionInterface)(nil).FindLiveByUserId), ctx, userId)
}

// IncrementFailure mocks base method.
func (m *MockPushSubscriptionInterface) IncrementFailure(ctx context.Context, id string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementFailure", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementFailure indicates an expected call of IncrementFailure.
func (mr *MockPushSubscriptionInterfaceMockRecorder) IncrementFailure(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementFailure", reflect.TypeOf((*MockPushSubscriptionInterface)(nil).IncrementFailure), ctx, id, at)
}

// MarkSuccess mocks base method.
func (m *MockPushSubscriptionInterface) MarkSuccess(ctx context.Context, id string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSuccess", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSuccess indicates an expected call of MarkSuccess.
func (mr *MockPushSubscriptionInterfaceMockRecorder) MarkSuccess(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSuccess", reflect.TypeOf((*MockPushSubscriptionInterface)(nil).MarkSuccess), ctx, id, at)
}

// Revoke mocks base method.
func (m *MockPushSubscriptionInterface) Revoke(ctx context.Context, id string, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockPushSubscriptionInterfaceMockRecorder) Revoke(ctx, id, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockPushSubscriptionInterface)(nil).Revoke), ctx, id, revokedAt)
}

// RevokeByUserIdAndEndpoint mocks base method.
func (m *MockPushSubscriptionInterface) RevokeByUserIdAndEndpoint(ctx context.Context, userId, endpoint string, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByUserIdAndEndpoint", ctx, userId, endpoint, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByUserIdAndEndpoint indicates an expected call of RevokeByUserIdAndEndpoint.
func (mr *MockPushSubscriptionInterfaceMockRecorder) RevokeByUserIdAndEndpoint(ctx, userId, endpoint, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByUserIdAndEndpoint", reflect.TypeOf((*MockPushSubscriptionInterface)(nil).RevokeByUserIdAndEndpoint), ctx, userId, endpoint, revokedAt)
}

// Upsert mocks base method.
func (m *MockPushSubscriptionInterface) Upsert(ctx context.Context, entity *entity.PushSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockPushSubscriptionInterfaceMockRecorder) Upsert(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockPushSubscriptionInterface)(nil).Upsert), ctx, entity)
}
