// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/push_delivery.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/push_delivery.go -destination=./internal/mock/mock_repository/push_delivery.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPushDeliveryInterface is a mock of PushDeliveryInterface interface.
type MockPushDeliveryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPushDeliveryInterfaceMockRecorder
	isgomock struct{}
}

// MockPushDeliveryInterfaceMockRecorder is the mock recorder for MockPushDeliveryInterface.
type MockPushDeliveryInterfaceMockRecorder struct {
	mock *MockPushDeliveryInterface
}

// NewMockPushDeliveryInterface creates a new mock instance.
func NewMockPushDeliveryInterface(ctrl *gomock.Controller) *MockPushDeliveryInterface {
	mock := &MockPushDeliveryInterface{ctrl: ctrl}
	mock.recorder = &MockPushDeliveryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushDeliveryInterface) EXPECT() *MockPushDeliveryInterfaceMockRecorder {
	return m.recorder
}

// CountNotificationsByUserIdAndCampaignsSince mocks base method.
func (m *MockPushDeliveryInterface) CountNotificationsByUserIdAndCampaignsSince(ctx context.Context, userId string, campaigns []string, since time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountNotificationsByUserIdAndCampaignsSince", ctx, userId, campaigns, since)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountNotificationsByUserIdAndCampaignsSince indicates an expected call of CountNotificationsByUserIdAndCampaignsSince.
func (mr *MockPushDeliveryInterfaceMockRecorder) CountNotificationsByUserIdAndCampaignsSince(ctx, userId, campaigns, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountNotificationsByUserIdAndCampaignsSince", reflect.TypeOf((*MockPushDeliveryInterface)(nil).CountNotificationsByUserIdAndCampaignsSince), ctx, userId, campaigns, since)
}

// DeleteByUserId mocks base method.
func (m *MockPushDeliveryInterface) DeleteByUserId(ctx context.Context, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserId", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserId indicates an expected call of DeleteByUserId.
func (mr *MockPushDeliveryInterfaceMockRecorder) DeleteByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserId", reflect.TypeOf((*MockPushDeliveryInterface)(nil).DeleteByUserId), ctx, uid)
}

// FindRecentByUserIdAndCampaign mocks base method.
func (m *MockPushDeliveryInterface) FindRecentByUserIdAndCampaign(ctx context.Context, userId, campaign string, limit int) ([]*entity.PushDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRecentByUserIdAndCampaign", ctx, userId, campaign, limit)
	ret0, _ := ret[0].([]*entity.PushDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRecentByUserIdAndCampaign indicates an expected call of FindRecentByUserIdAndCampaign.
func (mr *MockPushDeliveryInterfaceMockRecorder) FindRecentByUserIdAndCampaign(ctx, userId, campaign, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRecentByUserIdAndCampaign", reflect.TypeOf((*MockPushDeliveryInterface)(nil).FindRecentByUserIdAndCampaign), ctx, userId, campaign, limit)
}

// MarkClicked mocks base method.
func (m *MockPushDeliveryInterface) MarkClicked(ctx context.Context, id, userId string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkClicked", ctx, id, userId, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkClicked indicates an expected call of MarkClicked.
func (mr *MockPushDeliveryInterfaceMockRecorder) MarkClicked(ctx, id, userId, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkClicked", reflect.TypeOf((*MockPushDeliveryInterface)(nil).MarkClicked), ctx, id, userId, at)
}

// MarkDelivered mocks base method.
func (m *MockPushDeliveryInterface) MarkDelivered(ctx context.Context, id, userId string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDelivered", ctx, id, userId, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDelivered indicates an expected call of MarkDelivered.
func (mr *MockPushDeliveryInterfaceMockRecorder) MarkDelivered(ctx, id, userId, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDelivered", reflect.TypeOf((*MockPushDeliveryInterface)(nil).MarkDelivered), ctx, id, userId, at)
}

// Save mocks base method.
func (m *MockPushDeliveryInterface) Save(ctx context.Context, entity *entity.PushDelivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPushDeliveryInterfaceMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPushDeliveryInterface)(nil).Save), ctx, entity)
}

// UpdateResult mocks base method.
func (m *MockPushDeliveryInterface) UpdateResult(ctx context.Context, id, status string, statusCode int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResult", ctx, id, status, statusCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateResult indicates an expected call of UpdateResult.
func (mr *MockPushDeliveryInterfaceMockRecorder) UpdateResult(ctx, id, status, statusCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResult", reflect.TypeOf((*MockPushDeliveryInterface)(nil).UpdateResult), ctx, id, status, statusCode)
}
