// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/regulation.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/regulation.go -destination=./internal/mock/mock_repository/regulation.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRegulationInterface is a mock of RegulationInterface interface.
type MockRegulationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRegulationInterfaceMockRecorder
	isgomock struct{}
}

// MockRegulationInterfaceMockRecorder is the mock recorder for MockRegulationInterface.
type MockRegulationInterfaceMockRecorder struct {
	mock *MockRegulationInterface
}

// NewMockRegulationInterface creates a new mock instance.
func NewMockRegulationInterface(ctrl *gomock.Controller) *MockRegulationInterface {
	mock := &MockRegulationInterface{ctrl: ctrl}
	mock.recorder = &MockRegulationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegulationInterface) EXPECT() *MockRegulationInterfaceMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockRegulationInterface) Find(ctx context.Context) ([]*entity.Regulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]*entity.Regulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRegulationInterfaceMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRegulationInterface)(nil).Find), ctx)
}
