// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/tag.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/tag.go -destination=./internal/mock/mock_repository/tag.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTagInterface is a mock of TagInterface interface.
type MockTagInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTagInterfaceMockRecorder
	isgomock struct{}
}

// MockTagInterfaceMockRecorder is the mock recorder for MockTagInterface.
type MockTagInterfaceMockRecorder struct {
	mock *MockTagInterface
}

// NewMockTagInterface creates a new mock instance.
func NewMockTagInterface(ctrl *gomock.Controller) *MockTagInterface {
	mock := &MockTagInterface{ctrl: ctrl}
	mock.recorder = &MockTagInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagInterface) EXPECT() *MockTagInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTagInterface) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTagInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagInterface)(nil).Delete), ctx, id)
}

// DeleteByUserId mocks base method.
func (m *MockTagInterface) DeleteByUserId(ctx context.Context, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserId", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserId indicates an expected call of DeleteByUserId.
func (mr *MockTagInterfaceMockRecorder) DeleteByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserId", reflect.TypeOf((*MockTagInterface)(nil).DeleteByUserId), ctx, uid)
}

// FindAttachableByIds mocks base method.
func (m *MockTagInterface) FindAttachableByIds(ctx context.Context, ids []string, uid string) ([]*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAttachableByIds", ctx, ids, uid)
	ret0, _ := ret[0].([]*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAttachableByIds indicates an expected call of FindAttachableByIds.
func (mr *MockTagInterfaceMockRecorder) FindAttachableByIds(ctx, ids, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAttachableByIds", reflect.TypeOf((*MockTagInterface)(nil).FindAttachableByIds), ctx, ids, uid)
}

// FindById mocks base method.
func (m *MockTagInterface) FindById(ctx context.Context, id string) (*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockTagInterfaceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockTagInterface)(nil).FindById), ctx, id)
}

// FindByUserId mocks base method.
func (m *MockTagInterface) FindByUserId(ctx context.Context, uid string) ([]*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, uid)
	ret0, _ := ret[0].([]*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockTagInterfaceMockRecorder) FindByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockTagInterface)(nil).FindByUserId), ctx, uid)
}

// FindByUserIdAndName mocks base method.
func (m *MockTagInterface) FindByUserIdAndName(ctx context.Context, uid, name string) (*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIdAndName", ctx, uid, name)
	ret0, _ := ret[0].(*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIdAndName indicates an expected call of FindByUserIdAndName.
func (mr *MockTagInterfaceMockRecorder) FindByUserIdAndName(ctx, uid, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIdAndName", reflect.TypeOf((*MockTagInterface)(nil).FindByUserIdAndName), ctx, uid, name)
}

// FindPresets mocks base method.
func (m *MockTagInterface) FindPresets(ctx context.Context, category string) ([]*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPresets", ctx, category)
	ret0, _ := ret[0].([]*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPresets indicates an expected call of FindPresets.
func (mr *MockTagInterfaceMockRecorder) FindPresets(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPresets", reflect.TypeOf((*MockTagInterface)(nil).FindPresets), ctx, category)
}

// ReplaceDeckCodeTags mocks base method.
func (m *MockTagInterface) ReplaceDeckCodeTags(ctx context.Context, deckCodeId string, tagIds []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceDeckCodeTags", ctx, deckCodeId, tagIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceDeckCodeTags indicates an expected call of ReplaceDeckCodeTags.
func (mr *MockTagInterfaceMockRecorder) ReplaceDeckCodeTags(ctx, deckCodeId, tagIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceDeckCodeTags", reflect.TypeOf((*MockTagInterface)(nil).ReplaceDeckCodeTags), ctx, deckCodeId, tagIds)
}

// ReplaceDeckTags mocks base method.
func (m *MockTagInterface) ReplaceDeckTags(ctx context.Context, deckId string, tagIds []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceDeckTags", ctx, deckId, tagIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceDeckTags indicates an expected call of ReplaceDeckTags.
func (mr *MockTagInterfaceMockRecorder) ReplaceDeckTags(ctx, deckId, tagIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceDeckTags", reflect.TypeOf((*MockTagInterface)(nil).ReplaceDeckTags), ctx, deckId, tagIds)
}

// ReplaceMatchTags mocks base method.
func (m *MockTagInterface) ReplaceMatchTags(ctx context.Context, matchId string, tagIds []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceMatchTags", ctx, matchId, tagIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceMatchTags indicates an expected call of ReplaceMatchTags.
func (mr *MockTagInterfaceMockRecorder) ReplaceMatchTags(ctx, matchId, tagIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceMatchTags", reflect.TypeOf((*MockTagInterface)(nil).ReplaceMatchTags), ctx, matchId, tagIds)
}

// ReplaceRecordTags mocks base method.
func (m *MockTagInterface) ReplaceRecordTags(ctx context.Context, recordId string, tagIds []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceRecordTags", ctx, recordId, tagIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceRecordTags indicates an expected call of ReplaceRecordTags.
func (mr *MockTagInterfaceMockRecorder) ReplaceRecordTags(ctx, recordId, tagIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceRecordTags", reflect.TypeOf((*MockTagInterface)(nil).ReplaceRecordTags), ctx, recordId, tagIds)
}

// Save mocks base method.
func (m *MockTagInterface) Save(ctx context.Context, entity *entity.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockTagInterfaceMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTagInterface)(nil).Save), ctx, entity)
}
