// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/tonamel_event_store.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/tonamel_event_store.go -destination=./internal/mock/mock_repository/tonamel_event_store.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTonamelEventStoreInterface is a mock of TonamelEventStoreInterface interface.
type MockTonamelEventStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTonamelEventStoreInterfaceMockRecorder
	isgomock struct{}
}

// MockTonamelEventStoreInterfaceMockRecorder is the mock recorder for MockTonamelEventStoreInterface.
type MockTonamelEventStoreInterfaceMockRecorder struct {
	mock *MockTonamelEventStoreInterface
}

// NewMockTonamelEventStoreInterface creates a new mock instance.
func NewMockTonamelEventStoreInterface(ctrl *gomock.Controller) *MockTonamelEventStoreInterface {
	mock := &MockTonamelEventStoreInterface{ctrl: ctrl}
	mock.recorder = &MockTonamelEventStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTonamelEventStoreInterface) EXPECT() *MockTonamelEventStoreInterfaceMockRecorder {
	return m.recorder
}

// FindByIds mocks base method.
func (m *MockTonamelEventStoreInterface) FindByIds(ctx context.Context, ids []string) ([]*entity.TonamelEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIds", ctx, ids)
	ret0, _ := ret[0].([]*entity.TonamelEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIds indicates an expected call of FindByIds.
func (mr *MockTonamelEventStoreInterfaceMockRecorder) FindByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIds", reflect.TypeOf((*MockTonamelEventStoreInterface)(nil).FindByIds), ctx, ids)
}

// Save mocks base method.
func (m *MockTonamelEventStoreInterface) Save(ctx context.Context, tonamelEvent *entity.TonamelEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, tonamelEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockTonamelEventStoreInterfaceMockRecorder) Save(ctx, tonamelEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTonamelEventStoreInterface)(nil).Save), ctx, tonamelEvent)
}
