// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/unofficial_event.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/unofficial_event.go -destination=./internal/mock/mock_repository/unofficial_event.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUnofficialEventInterface is a mock of UnofficialEventInterface interface.
type MockUnofficialEventInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUnofficialEventInterfaceMockRecorder
	isgomock struct{}
}

// MockUnofficialEventInterfaceMockRecorder is the mock recorder for MockUnofficialEventInterface.
type MockUnofficialEventInterfaceMockRecorder struct {
	mock *MockUnofficialEventInterface
}

// NewMockUnofficialEventInterface creates a new mock instance.
func NewMockUnofficialEventInterface(ctrl *gomock.Controller) *MockUnofficialEventInterface {
	mock := &MockUnofficialEventInterface{ctrl: ctrl}
	mock.recorder = &MockUnofficialEventInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnofficialEventInterface) EXPECT() *MockUnofficialEventInterfaceMockRecorder {
	return m.recorder
}

// FindById mocks base method.
func (m *MockUnofficialEventInterface) FindById(ctx context.Context, id string) (*entity.UnofficialEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*entity.UnofficialEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockUnofficialEventInterfaceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockUnofficialEventInterface)(nil).FindById), ctx, id)
}

// Save mocks base method.
func (m *MockUnofficialEventInterface) Save(ctx context.Context, entity *entity.UnofficialEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUnofficialEventInterfaceMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUnofficialEventInterface)(nil).Save), ctx, entity)
}
