// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/user_stat.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/user_stat.go -destination=./internal/mock/mock_repository/user_stat.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStatInterface is a mock of UserStatInterface interface.
type MockUserStatInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserStatInterfaceMockRecorder
	isgomock struct{}
}

// MockUserStatInterfaceMockRecorder is the mock recorder for MockUserStatInterface.
type MockUserStatInterfaceMockRecorder struct {
	mock *MockUserStatInterface
}

// NewMockUserStatInterface creates a new mock instance.
func NewMockUserStatInterface(ctrl *gomock.Controller) *MockUserStatInterface {
	mock := &MockUserStatInterface{ctrl: ctrl}
	mock.recorder = &MockUserStatInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStatInterface) EXPECT() *MockUserStatInterfaceMockRecorder {
	return m.recorder
}

// FindUserStat mocks base method.
func (m *MockUserStatInterface) FindUserStat(ctx context.Context, userId string, fromDate, toDate time.Time) (*entity.UserStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserStat", ctx, userId, fromDate, toDate)
	ret0, _ := ret[0].(*entity.UserStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserStat indicates an expected call of FindUserStat.
func (mr *MockUserStatInterfaceMockRecorder) FindUserStat(ctx, userId, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserStat", reflect.TypeOf((*MockUserStatInterface)(nil).FindUserStat), ctx, userId, fromDate, toDate)
}
