// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/user_stat_recent.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/user_stat_recent.go -destination=./internal/mock/mock_repository/user_stat_recent.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStatRecentInterface is a mock of UserStatRecentInterface interface.
type MockUserStatRecentInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserStatRecentInterfaceMockRecorder
	isgomock struct{}
}

// MockUserStatRecentInterfaceMockRecorder is the mock recorder for MockUserStatRecentInterface.
type MockUserStatRecentInterfaceMockRecorder struct {
	mock *MockUserStatRecentInterface
}

// NewMockUserStatRecentInterface creates a new mock instance.
func NewMockUserStatRecentInterface(ctrl *gomock.Controller) *MockUserStatRecentInterface {
	mock := &MockUserStatRecentInterface{ctrl: ctrl}
	mock.recorder = &MockUserStatRecentInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStatRecentInterface) EXPECT() *MockUserStatRecentInterfaceMockRecorder {
	return m.recorder
}

// FindRecentMatches mocks base method.
func (m *MockUserStatRecentInterface) FindRecentMatches(ctx context.Context, userId string, count int, deckId string) ([]*entity.RecentMatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRecentMatches", ctx, userId, count, deckId)
	ret0, _ := ret[0].([]*entity.RecentMatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRecentMatches indicates an expected call of FindRecentMatches.
func (mr *MockUserStatRecentInterfaceMockRecorder) FindRecentMatches(ctx, userId, count, deckId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRecentMatches", reflect.TypeOf((*MockUserStatRecentInterface)(nil).FindRecentMatches), ctx, userId, count, deckId)
}
