// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/user_environment_badge.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/user_environment_badge.go -destination=./internal/mock/mock_repository/user_environment_badge.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserEnvironmentBadgeInterface is a mock of UserEnvironmentBadgeInterface interface.
type MockUserEnvironmentBadgeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserEnvironmentBadgeInterfaceMockRecorder
	isgomock struct{}
}

// MockUserEnvironmentBadgeInterfaceMockRecorder is the mock recorder for MockUserEnvironmentBadgeInterface.
type MockUserEnvironmentBadgeInterfaceMockRecorder struct {
	mock *MockUserEnvironmentBadgeInterface
}

// NewMockUserEnvironmentBadgeInterface creates a new mock instance.
func NewMockUserEnvironmentBadgeInterface(ctrl *gomock.Controller) *MockUserEnvironmentBadgeInterface {
	mock := &MockUserEnvironmentBadgeInterface{ctrl: ctrl}
	mock.recorder = &MockUserEnvironmentBadgeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserEnvironmentBadgeInterface) EXPECT() *MockUserEnvironmentBadgeInterfaceMockRecorder {
	return m.recorder
}

// FindByUserId mocks base method.
func (m *MockUserEnvironmentBadgeInterface) FindByUserId(ctx context.Context, userId string) ([]*entity.UserEnvironmentBadge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, userId)
	ret0, _ := ret[0].([]*entity.UserEnvironmentBadge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockUserEnvironmentBadgeInterfaceMockRecorder) FindByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockUserEnvironmentBadgeInterface)(nil).FindByUserId), ctx, userId)
}

// Save mocks base method.
func (m *MockUserEnvironmentBadgeInterface) Save(ctx context.Context, entity *entity.UserEnvironmentBadge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserEnvironmentBadgeInterfaceMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserEnvironmentBadgeInterface)(nil).Save), ctx, entity)
}
