// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/user_streak.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/user_streak.go -destination=./internal/mock/mock_repository/user_streak.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStreakInterface is a mock of UserStreakInterface interface.
type MockUserStreakInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserStreakInterfaceMockRecorder
	isgomock struct{}
}

// MockUserStreakInterfaceMockRecorder is the mock recorder for MockUserStreakInterface.
type MockUserStreakInterfaceMockRecorder struct {
	mock *MockUserStreakInterface
}

// NewMockUserStreakInterface creates a new mock instance.
func NewMockUserStreakInterface(ctrl *gomock.Controller) *MockUserStreakInterface {
	mock := &MockUserStreakInterface{ctrl: ctrl}
	mock.recorder = &MockUserStreakInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStreakInterface) EXPECT() *MockUserStreakInterfaceMockRecorder {
	return m.recorder
}

// FindByUserId mocks base method.
func (m *MockUserStreakInterface) FindByUserId(ctx context.Context, userId string) (*entity.UserStreak, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, userId)
	ret0, _ := ret[0].(*entity.UserStreak)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockUserStreakInterfaceMockRecorder) FindByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockUserStreakInterface)(nil).FindByUserId), ctx, userId)
}

// Save mocks base method.
func (m *MockUserStreakInterface) Save(ctx context.Context, entity *entity.UserStreak) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserStreakInterfaceMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserStreakInterface)(nil).Save), ctx, entity)
}
