// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/user_player.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/user_player.go -destination=./internal/mock/mock_repository/user_player.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserPlayerInterface is a mock of UserPlayerInterface interface.
type MockUserPlayerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserPlayerInterfaceMockRecorder
	isgomock struct{}
}

// MockUserPlayerInterfaceMockRecorder is the mock recorder for MockUserPlayerInterface.
type MockUserPlayerInterfaceMockRecorder struct {
	mock *MockUserPlayerInterface
}

// NewMockUserPlayerInterface creates a new mock instance.
func NewMockUserPlayerInterface(ctrl *gomock.Controller) *MockUserPlayerInterface {
	mock := &MockUserPlayerInterface{ctrl: ctrl}
	mock.recorder = &MockUserPlayerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPlayerInterface) EXPECT() *MockUserPlayerInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserPlayerInterface) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserPlayerInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserPlayerInterface)(nil).Delete), ctx, id)
}

// ExistsActiveByPlayerId mocks base method.
func (m *MockUserPlayerInterface) ExistsActiveByPlayerId(ctx context.Context, playerId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsActiveByPlayerId", ctx, playerId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsActiveByPlayerId indicates an expected call of ExistsActiveByPlayerId.
func (mr *MockUserPlayerInterfaceMockRecorder) ExistsActiveByPlayerId(ctx, playerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsActiveByPlayerId", reflect.TypeOf((*MockUserPlayerInterface)(nil).ExistsActiveByPlayerId), ctx, playerId)
}

// FindByUserId mocks base method.
func (m *MockUserPlayerInterface) FindByUserId(ctx context.Context, userId string) (*entity.UserPlayer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, userId)
	ret0, _ := ret[0].(*entity.UserPlayer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockUserPlayerInterfaceMockRecorder) FindByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockUserPlayerInterface)(nil).FindByUserId), ctx, userId)
}

// Save mocks base method.
func (m *MockUserPlayerInterface) Save(ctx context.Context, entity *entity.UserPlayer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserPlayerInterfaceMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserPlayerInterface)(nil).Save), ctx, entity)
}
