// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/user_stat_history.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/user_stat_history.go -destination=./internal/mock/mock_repository/user_stat_history.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStatHistoryInterface is a mock of UserStatHistoryInterface interface.
type MockUserStatHistoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserStatHistoryInterfaceMockRecorder
	isgomock struct{}
}

// MockUserStatHistoryInterfaceMockRecorder is the mock recorder for MockUserStatHistoryInterface.
type MockUserStatHistoryInterfaceMockRecorder struct {
	mock *MockUserStatHistoryInterface
}

// NewMockUserStatHistoryInterface creates a new mock instance.
func NewMockUserStatHistoryInterface(ctrl *gomock.Controller) *MockUserStatHistoryInterface {
	mock := &MockUserStatHistoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserStatHistoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStatHistoryInterface) EXPECT() *MockUserStatHistoryInterfaceMockRecorder {
	return m.recorder
}

// FindUserStatHistory mocks base method.
func (m *MockUserStatHistoryInterface) FindUserStatHistory(ctx context.Context, userId string, fromDate, toDate time.Time, deckId string) ([]*entity.UserStatMonthly, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserStatHistory", ctx, userId, fromDate, toDate, deckId)
	ret0, _ := ret[0].([]*entity.UserStatMonthly)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserStatHistory indicates an expected call of FindUserStatHistory.
func (mr *MockUserStatHistoryInterfaceMockRecorder) FindUserStatHistory(ctx, userId, fromDate, toDate, deckId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserStatHistory", reflect.TypeOf((*MockUserStatHistoryInterface)(nil).FindUserStatHistory), ctx, userId, fromDate, toDate, deckId)
}
