// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/user_daily_activity.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/user_daily_activity.go -destination=./internal/mock/mock_repository/user_daily_activity.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserDailyActivityInterface is a mock of UserDailyActivityInterface interface.
type MockUserDailyActivityInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserDailyActivityInterfaceMockRecorder
	isgomock struct{}
}

// MockUserDailyActivityInterfaceMockRecorder is the mock recorder for MockUserDailyActivityInterface.
type MockUserDailyActivityInterfaceMockRecorder struct {
	mock *MockUserDailyActivityInterface
}

// NewMockUserDailyActivityInterface creates a new mock instance.
func NewMockUserDailyActivityInterface(ctrl *gomock.Controller) *MockUserDailyActivityInterface {
	mock := &MockUserDailyActivityInterface{ctrl: ctrl}
	mock.recorder = &MockUserDailyActivityInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDailyActivityInterface) EXPECT() *MockUserDailyActivityInterfaceMockRecorder {
	return m.recorder
}

// DeleteByUserId mocks base method.
func (m *MockUserDailyActivityInterface) DeleteByUserId(ctx context.Context, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserId", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserId indicates an expected call of DeleteByUserId.
func (mr *MockUserDailyActivityInterfaceMockRecorder) DeleteByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserId", reflect.TypeOf((*MockUserDailyActivityInterface)(nil).DeleteByUserId), ctx, uid)
}

// Touch mocks base method.
func (m *MockUserDailyActivityInterface) Touch(ctx context.Context, entities []*entity.UserDailyActivity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// Touch indicates an expected call of Touch.
func (mr *MockUserDailyActivityInterfaceMockRecorder) Touch(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockUserDailyActivityInterface)(nil).Touch), ctx, entities)
}
