// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/user_gym.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/user_gym.go -destination=./internal/mock/mock_repository/user_gym.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserGymInterface is a mock of UserGymInterface interface.
type MockUserGymInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserGymInterfaceMockRecorder
	isgomock struct{}
}

// MockUserGymInterfaceMockRecorder is the mock recorder for MockUserGymInterface.
type MockUserGymInterfaceMockRecorder struct {
	mock *MockUserGymInterface
}

// NewMockUserGymInterface creates a new mock instance.
func NewMockUserGymInterface(ctrl *gomock.Controller) *MockUserGymInterface {
	mock := &MockUserGymInterface{ctrl: ctrl}
	mock.recorder = &MockUserGymInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserGymInterface) EXPECT() *MockUserGymInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserGymInterface) Create(ctx context.Context, entity *entity.UserGym) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserGymInterfaceMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserGymInterface)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockUserGymInterface) Delete(ctx context.Context, uid string, shopId uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uid, shopId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserGymInterfaceMockRecorder) Delete(ctx, uid, shopId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserGymInterface)(nil).Delete), ctx, uid, shopId)
}

// DeleteByUserId mocks base method.
func (m *MockUserGymInterface) DeleteByUserId(ctx context.Context, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserId", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserId indicates an expected call of DeleteByUserId.
func (mr *MockUserGymInterfaceMockRecorder) DeleteByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserId", reflect.TypeOf((*MockUserGymInterface)(nil).DeleteByUserId), ctx, uid)
}

// FindByUserId mocks base method.
func (m *MockUserGymInterface) FindByUserId(ctx context.Context, uid string) ([]*entity.UserGymView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, uid)
	ret0, _ := ret[0].([]*entity.UserGymView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockUserGymInterfaceMockRecorder) FindByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockUserGymInterface)(nil).FindByUserId), ctx, uid)
}
