// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/user_favorite_deck.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/user_favorite_deck.go -destination=./internal/mock/mock_repository/user_favorite_deck.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserFavoriteDeckInterface is a mock of UserFavoriteDeckInterface interface.
type MockUserFavoriteDeckInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserFavoriteDeckInterfaceMockRecorder
	isgomock struct{}
}

// MockUserFavoriteDeckInterfaceMockRecorder is the mock recorder for MockUserFavoriteDeckInterface.
type MockUserFavoriteDeckInterfaceMockRecorder struct {
	mock *MockUserFavoriteDeckInterface
}

// NewMockUserFavoriteDeckInterface creates a new mock instance.
func NewMockUserFavoriteDeckInterface(ctrl *gomock.Controller) *MockUserFavoriteDeckInterface {
	mock := &MockUserFavoriteDeckInterface{ctrl: ctrl}
	mock.recorder = &MockUserFavoriteDeckInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFavoriteDeckInterface) EXPECT() *MockUserFavoriteDeckInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserFavoriteDeckInterface) Create(ctx context.Context, entity *entity.UserFavoriteDeck) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserFavoriteDeckInterfaceMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserFavoriteDeckInterface)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockUserFavoriteDeckInterface) Delete(ctx context.Context, uid, deckId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uid, deckId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserFavoriteDeckInterfaceMockRecorder) Delete(ctx, uid, deckId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserFavoriteDeckInterface)(nil).Delete), ctx, uid, deckId)
}

// DeleteByUserId mocks base method.
func (m *MockUserFavoriteDeckInterface) DeleteByUserId(ctx context.Context, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserId", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserId indicates an expected call of DeleteByUserId.
func (mr *MockUserFavoriteDeckInterfaceMockRecorder) DeleteByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserId", reflect.TypeOf((*MockUserFavoriteDeckInterface)(nil).DeleteByUserId), ctx, uid)
}

// FindByUserId mocks base method.
func (m *MockUserFavoriteDeckInterface) FindByUserId(ctx context.Context, uid string) ([]*entity.UserFavoriteDeck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, uid)
	ret0, _ := ret[0].([]*entity.UserFavoriteDeck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockUserFavoriteDeckInterfaceMockRecorder) FindByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockUserFavoriteDeckInterface)(nil).FindByUserId), ctx, uid)
}
