// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/user_acquisition.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/user_acquisition.go -destination=./internal/mock/mock_repository/user_acquisition.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserAcquisitionInterface is a mock of UserAcquisitionInterface interface.
type MockUserAcquisitionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserAcquisitionInterfaceMockRecorder
	isgomock struct{}
}

// MockUserAcquisitionInterfaceMockRecorder is the mock recorder for MockUserAcquisitionInterface.
type MockUserAcquisitionInterfaceMockRecorder struct {
	mock *MockUserAcquisitionInterface
}

// NewMockUserAcquisitionInterface creates a new mock instance.
func NewMockUserAcquisitionInterface(ctrl *gomock.Controller) *MockUserAcquisitionInterface {
	mock := &MockUserAcquisitionInterface{ctrl: ctrl}
	mock.recorder = &MockUserAcquisitionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAcquisitionInterface) EXPECT() *MockUserAcquisitionInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserAcquisitionInterface) Create(ctx context.Context, entity *entity.UserAcquisition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserAcquisitionInterfaceMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserAcquisitionInterface)(nil).Create), ctx, entity)
}

// DeleteByUserId mocks base method.
func (m *MockUserAcquisitionInterface) DeleteByUserId(ctx context.Context, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserId", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserId indicates an expected call of DeleteByUserId.
func (mr *MockUserAcquisitionInterfaceMockRecorder) DeleteByUserId(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserId", reflect.TypeOf((*MockUserAcquisitionInterface)(nil).DeleteByUserId), ctx, uid)
}

// SaveSurveyAnswer mocks base method.
func (m *MockUserAcquisitionInterface) SaveSurveyAnswer(ctx context.Context, uid, answer string, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSurveyAnswer", ctx, uid, answer, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSurveyAnswer indicates an expected call of SaveSurveyAnswer.
func (mr *MockUserAcquisitionInterfaceMockRecorder) SaveSurveyAnswer(ctx, uid, answer, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSurveyAnswer", reflect.TypeOf((*MockUserAcquisitionInterface)(nil).SaveSurveyAnswer), ctx, uid, answer, now)
}
