// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/user_badge.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/user_badge.go -destination=./internal/mock/mock_repository/user_badge.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserBadgeInterface is a mock of UserBadgeInterface interface.
type MockUserBadgeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserBadgeInterfaceMockRecorder
	isgomock struct{}
}

// MockUserBadgeInterfaceMockRecorder is the mock recorder for MockUserBadgeInterface.
type MockUserBadgeInterfaceMockRecorder struct {
	mock *MockUserBadgeInterface
}

// NewMockUserBadgeInterface creates a new mock instance.
func NewMockUserBadgeInterface(ctrl *gomock.Controller) *MockUserBadgeInterface {
	mock := &MockUserBadgeInterface{ctrl: ctrl}
	mock.recorder = &MockUserBadgeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserBadgeInterface) EXPECT() *MockUserBadgeInterfaceMockRecorder {
	return m.recorder
}

// FindByUserId mocks base method.
func (m *MockUserBadgeInterface) FindByUserId(ctx context.Context, userId string) ([]*entity.UserBadge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, userId)
	ret0, _ := ret[0].([]*entity.UserBadge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockUserBadgeInterfaceMockRecorder) FindByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockUserBadgeInterface)(nil).FindByUserId), ctx, userId)
}

// Save mocks base method.
func (m *MockUserBadgeInterface) Save(ctx context.Context, entity *entity.UserBadge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserBadgeInterfaceMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserBadgeInterface)(nil).Save), ctx, entity)
}
