// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/weekly_deck_usage_stat.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repository/weekly_deck_usage_stat.go -destination=./internal/mock/mock_repository/weekly_deck_usage_stat.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/vsrecorder/core-apiserver/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockWeeklyDeckUsageStatInterface is a mock of WeeklyDeckUsageStatInterface interface.
type MockWeeklyDeckUsageStatInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWeeklyDeckUsageStatInterfaceMockRecorder
	isgomock struct{}
}

// MockWeeklyDeckUsageStatInterfaceMockRecorder is the mock recorder for MockWeeklyDeckUsageStatInterface.
type MockWeeklyDeckUsageStatInterfaceMockRecorder struct {
	mock *MockWeeklyDeckUsageStatInterface
}

// NewMockWeeklyDeckUsageStatInterface creates a new mock instance.
func NewMockWeeklyDeckUsageStatInterface(ctrl *gomock.Controller) *MockWeeklyDeckUsageStatInterface {
	mock := &MockWeeklyDeckUsageStatInterface{ctrl: ctrl}
	mock.recorder = &MockWeeklyDeckUsageStatInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeeklyDeckUsageStatInterface) EXPECT() *MockWeeklyDeckUsageStatInterfaceMockRecorder {
	return m.recorder
}

// FindWeeklyDeckUsageStat mocks base method.
func (m *MockWeeklyDeckUsageStatInterface) FindWeeklyDeckUsageStat(ctx context.Context, fromDate, toDate time.Time) (*entity.WeeklyDeckUsageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWeeklyDeckUsageStat", ctx, fromDate, toDate)
	ret0, _ := ret[0].(*entity.WeeklyDeckUsageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWeeklyDeckUsageStat indicates an expected call of FindWeeklyDeckUsageStat.
func (mr *MockWeeklyDeckUsageStatInterfaceMockRecorder) FindWeeklyDeckUsageStat(ctx, fromDate, toDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWeeklyDeckUsageStat", reflect.TypeOf((*MockWeeklyDeckUsageStatInterface)(nil).FindWeeklyDeckUsageStat), ctx, fromDate, toDate)
}
